= Paper1

The interplay between recurring atmospheric processes and local topography creates regular observable climatic phenomena. We present a novel method for analyzing the spatial distribution of atmospheric parameters at the mesoscale which will allows for the extraction of a pair of underlying climate-associated shapes. These shapes act as unique fingerprints that allow one to observe climate without having to characterize it. Key to making this leap is to note that many climate systems phenomena come in non-coocurring pairs. For instance the Summer/Winter Monsoons, El Nino / La Nina and the positive and negative phases of many climate dipoles. The presence of one climate state precludes the occurance of the other. As a result of this bistability, when reducing the measured climate parameter to two dimensions (by singular value decompositon) we will observe clustering around two linear combinations of the basis vectors. The combinations can be inferred with a variance minimizing search, and in the absence of any tertiary climate phenomena, these combinations will correspond to best estimates of the underlying climate-induced patterns. In so doing we correct for the inherant deficiencies of the vectors derived in a typical EOF analysis. Once extracted, we can measure the presence of these shapes in the original data and build a two state climate index. Lastly, we demonstrate how to estimate the noise induces error at each index value and present several examples using the IMERG presciptiation dataset. An  accompanying program for reproducing the analysis is provided
