:docinfo: shared
:imagesdir: ../fig/
:!webfonts:
:stylesheet: ../web/adoc.css
:table-caption!:
:reproducible:
:nofooter:

= Paper1
George Kontsevich

== Abstract

The interplay of climate and topography strongly affects weather's spatial variability,
causing large climate systems to have a recurring fingerprint on regional weather.
If identified a priori,
an observer of the weather may infer which climate system is active at any given time.
Building on the singular value decomposition (SVD),
we present a new method for estimating these climate-associated patterns.
Mirroring the design of empirical orthogonal function (EOF) analysis,
to ensure the method is region agnostic we eshew tuning parameters and heuristics.
Key to the approach is recognizing that many climate phenomena come in non-coocurring pairs.
When reduced to two dimensions by SVD,
weather records cluster around two linear combinations of the basis vectors.
These combinations,
once isolated,
form the basis of a regional two-state climate index.
We present several examples using the IMERG precipitation dataset.
An accompanying program for reproducing the analysis is provided.


WORD LIMIT: 150
WORDS: 149

== Introduction

Climate systems,
such at the monsoons or El Nino/La Nina,
acquired their names when people native to a region noted recurring weather phenomena.
The typical modern approach is search for and then characterize repeated atmospheric configurations.
However the original methodology,
of pattern recognition comes naturally to the untrained eye.
Arguably it still presents several distinct advantages.
Chief among them are its generality and simplicity.
Pattern recognition,
as applied in the atmospheric sciences,
has chiefly been performed using empirical orthogonal function (EOF) analysis.
This is done by doing a singular value decomposition (SVD) of some parameter's anomaly from a mean.
The SVD works in an iterative fashion,
calculating the induced matrix norm of the dataset,
removing it from the data and then repeating the process.
For a single signal system this produces a good approximation of the underlying signal.
However,
weather records often have contain multiple climate signals.
EOF results are often not meeting expectations.
Often the first EOF is used and subsequent ones are discarded.
The most critical issues affecting the resulting patterns and their interpretations are as follows:

O1:: EOF patterns are orthogonal,
climate-associated patterns are generally not.
O2:: All EOF patterns,
including EOF1,
will represent mixtures of all underlying signals
O3:: EOF1 is typically heavily biased towards the strongest signal,
giving the impression it is correct.
O4:: Changes in EOF intensity over time often make it seem like climate phenomena have some sort of phase-lag,
but this is in fact an artifact due to poor climate pattern separation.

The reliance on the anomaly is another typical source of issues.
As will become clear,
mean structure does not typically represent any physical process.
A mean will contain a mixture of all the regional climate patterns;
at a ratio that is not known a priori.
Removing the mean,
to calculate an anomaly,
in effect introduces some constant amount of each underlying climate signal to all your observations.
Meanwhile,
the climate associated patterns actually manifesting will be vary in intensity over time.
Once operating on the anomaly,
disentangling the unknown constant factors and the varying patterns complicates the analysis.
To sidestep this issue,
we confine ourselves to the using the SVD on the original data observations directly.
This means that instead of EOF1, EOF2, .. etc. we will use the singular vectors SV1 SV2 .. etc.

That said,
all the aforelisted issues (O1..4) hold just as well for the SVD as for the EOF.

== Materials

- We first illustrate the critical issues with EOF-like analyses using synthetic data.
Synthetic data allows us to know a-priori which climate patterns are present;
in other words we know what we are looking for.
We can observe issues that occur and start constructing a solution for how to resolve them.

- For the main case study we look at precipitation over Peninsular Southern Thailand.
The top of the Malay Peninsula is climatologically challenging.
It is subject to two distinct monsoon systems:
The dominant monsoon system is the so-called summer monsoon
(ie. boreal summer).
This brings moisture from the Indian Ocean and Adamant Sea.
The secondary system is the winter monsoon,
which brings moisture from the East
- the South China Sea and the Gulf of Thailand.

- To help us demonstrate an improvement over the EOF,
we stress test the method using gridded precipitation data.
For this we use the IMERG Late dataset. (SUPP: Notes on IMERG)
While we don't observe sensitivity with regard to time,
for clarity daily accumulations are binned in to pentads and the leap day has been removed.
(SUPP Pattern separation at different time scales)
High density mesoscale data will be essential for pattern stability.
When observing regions that are too large,
climate phenomena cease to take effect simultaneously across the whole area of interest.
Larger fractions of the observation time will begin to include incomplete/smeared climate associated patterns.
As a result it becomes more difficult to isolation fixed patterns and energy "leaks" into secondary modes.
On the other hand,
small/mesoscale regions typically exhibit very faster climate system onset and withdrawal.
For instance across the observed southern Thai geogrid the monsoon onset will happen over the course of just several days. (REF)
IMERG has a 0.1x0.1 degree resolution which gives ample room to select small regions of interest.

.Supplementary sections explore:
The Great Rift Valley:: A region with semi non seasonal climate signals.
Marrah Mountains (Sudan):: A region with one climate phenomena and the breakdown in one of the EOF assumptions.
Java Island:: Diurnal cycles with large errors and less stationary patterns
ERA5 reanalysis precipitation:: The method as used to validate climate model output
IMERG Final Result:: Showing artifacts caused by numerical normalization procedures


== Synthetic illustrations of the EOF/SVD problem

Using a synthetic dataset allows us to not only observe the aformentioned problems (O1..4),
but it will also give us insight in to a possible solution.
We start by creating two arbitrary patterns,
representing the two states of our climate system.
Since the pattern are arbitrary,
they are not orthogonal to each other.
This points us already to issue *O1*.
These patterns are then perturbed to create synthetic "observations".
For ease of interpretability,
the observations are arranged to mimick monthly accumulation of a monsoonal region.
First there are several summer-equivalent patterned observations.
This is followed by a shorter period of winter-equivalent patterned observations.
What is surprising is that the SVD
(and the equivalent EOF method)
produce two basis vectors that do look like a mixture of our original patterns.

FIGURE

The SVD algorithm can be viewed as an interative algorithm,
which builds singular vectors sequentially.
Once a singular vector is created it is removed from the observations.
The algorithm is then repeated on the adjusted observations to make the next singular vector.
Removing the singular vector from the data causes the remaining data to be orthogonal,
and hence causes the subsequent basis vector to be orthogonal.
This goes to the root of problem *O1*

The first thing that may be of surprise is the negative values in the first singular vector (SV1).
These values,
colored in blue,
are characteristic of most SVD numerical routines.
Most such routines,
such as the Intel MKL library used here,
will return negative values for the first singular vector.
However in actuality,
as a basis vector,
the signs could be safely inverted without changing the result.

The next surprise is that the first singular looks very incorrect.
It looks like a mixture of the two starting patterns.
To understand the root of the problem we need to look at what the SVD does at each iteration.
When building a singular vector,
for instance when building SV1,
the SVD is fundamentally doing a weighted average of the data.
The weighting is said to maximizes the induced matrix norm (REF)
In other words,
the weights are selected such that the euclidean length
(2-norm)
of the resulting singular vector is maximized.
This at face value seems to encourage observations with similar image to be added up together.
The patterns will add up constructively and return a best estimate.
Since the resuling vector is best interpreted as a pattern image,
it may be easier to reinterpret this as a maximizing of the sum of the squares of all the pixels.
The algorithmic constraint
(so that you can not pick arbitrarily large weights)
is that the vector of your weights must be of unit length.
In other words,
the sum of the squares of the weights is equal to `1.0`.
This kind of constraint means that the direct "normal" sum of weights is not constant.
All else being equal,
spreading weights out actually makes their sum a higher value.
This is most easily illustrated by looking at the logical extremes.
If all weight were assigned to one observation
(for instance the one with the highest value)
and all other weights were set to zero,
then the sum of weights would equal `1.0`
(same as the sum of squares).
By contrast,
an even spread of weights across all `N` observation would give each weight the size `1/sqrt(N)`
(here the sum of squares still equals 1.0 for any value of `N`)
Since `N/sqrt(N) > 1.0` for all values of `N`>`1` the algorithm has a tendency to spread weights.
So while the observations that exhibit the dominant do get higher weights,
observations with secondary signals will get small weights assigned to them as well.
Though they don't sum constructively with the dominant signal,
spreading the weights does in effect increases the total sum of all the weights.

The end result is our SV1 vector ends up looking like a mixture of both underlying signals;
highlighting our issue *O2*.
This mixing effect seems to diminish rapidly as the difference between climate signals increases;
which points is to issue *O3*
The mixing ratio is not something we have any analytic insight into.

The next even more glaring issue is the second Singular Vector (SV2).
SV1 is some unknown mixture of the two patterns.
Since the algorithm works in an interative fashion,
these mixture of patterns was removed from the observations because SV2 was constructed.
Since the adjusted observations are now orthogonal to the first mixture,
we in effect have no hope of reconstructing a pattern.
However the end result interestingly enough looks like a different mixture of the two original patterns.

This last observation,
that both SVs are different mixtures of the underlying signals,
ends up being the critical piece of information that allows us to correct for the problem.

Because of this recurring signal-mixture issue,
directly observing how SV1 and SV2 change over time is a common source of false interpretations.
This is issue *O4*.
We leave a more details discussion for (SUPP)

== Case Study: South East Asian monsoon systems

We now repeat the same analysis on a real-world example in southern Thailand.
Here we don't have a priori knowledge of the climate associate patterns.
However,
we do have a high level understanding of the climate configuration.
Combining the two should allow us to confirm the SVD/EOF problems.
Once confirmed,
we can construct a easily interpretable correction.
This will produce patterns with a much higher fidelity to those we observe in the raw data.

A preliminary visual inspection shows us that there are two distinct patterns.
The summer months have rain on the west coast,
predominantly in the northern-most part of the region.
The late fall and early winter months show rain in the south-eastern section.
These two rain patterns correspond to summer and winter monsoon systems.
At a high level,
the pattern are a result of the complex interplay between the local topography and the seasonal synoptic scale atmospheric conditions.
In this particular case,
the areas with the highest rainfall correspond to coastal high mountains downwind of their corresponding monsoonal systems.

However,
while complex land-air interactions are underway,
an observer does not need to understand them to visually identify the climates in question.
The patterns are evident without any understanding of the physical mechanisms behind them.
This suggests that we should be able to estimate climate-associated patterns without understanding them.
The motivation for this is severalfold.
For one,
such a method would present an objective,
climate-agnostic,
first step in observing climate systems.
We would entirely avoid needing to characterize the climate system in question;
obviating the need for heuristics or thresholding systems based on past statistics
**(Rainy Season of the Asian Pacific Summer Monsoon - Bin Wang)**.
Furthermore,
we should be able to leverage more data and get higher fidelity than typical conservative methods,
such as JJA or DJF means.
Aspirationally,
we may in theory be able to explore new climate processes that have not yet been identified/characterized.

As in the synthetic example,
we first try to extract the underlying patterns by SVD.
The first singular vector gives us a shape that looks encouraging.
The shape at face value seems similar to the west coast precipitation associate with the summer monsoon.
Often an EOF anaylsis would stop at this point as the result doesn't have obvious glaring issues.
While our synethetic example showed that mixing must be happening due to issue *O2*,
it is not immediately apparent due to a couple of reasons.
First,
unlike in the more balanced synthetic example,
here summer monsoon rain is a dominant fraction of the annual total.
Issue *O3* strongly preserves the pattern.
Second,
unlike in our simple synthetic example natural patterns are typically smooth.
As a result their mixtures do not make large glaring artifacts.
However,
here a careful eye will note an issue.
When looking at the first singular vector,
it shows a small intensification of precipitation on the East coast which is not apparent in summer months.

The second singular vector,
orthogonal to the first,
shows some very strong east west contrast and but doesn't immediately look like any climate system.
The large negative values in the north west can't be directly interpreted as they don't make physical sense for precipitation.
Since we aren't working off an anomaly
(like in an EOF analysis)
the climate-associated patterns of precipitation should be positive.
Inverting the vector's values doesn't solve the issue as it would just creates other negative zones.

If we look at how SV1 and SV2 values change over time,
we will see a spurious relationship between the two.
Interpretting SV1 and SV2 as indicative of distinct climate phenomena may lead one to believe SV2 drives SV1.
If the signals are further normalized,
then this pattern can be misinterpreted as a phase-lag and create a false link between climate systems (REF: MARTIME CONTINENT PAPER)

EXPAND ON IN SUPP?

== Isolating correct patterns in the SV subspace

We already know,
from our synthetic example,
that the root cause of the observed problems with the singular vectors stem from them representing mixtures of the underlying climate signals (*O2*).

Unless you are in a region with a single dominant climate system,
the singular vectors can not be safely used directly.
Unfortunately there is no simple way to differentiate single climate systems from ones with climate dipoles.
Such situations need to be identified by the researcher on a case-by-case basis.
For an indepth look at the challenges presented by single system regions,
please see the Marrah Plateau example in **SUPP**

To isolate the climate systems we need to assume three simplifying characteristics:

A1:: the local climate system can be approximation as a noise dominated system of two signals.

A2:: these two climate systems by-in-large don't undergo any mixing.
In other words the two climates can't coocur.

A3:: The climate patterns in question scale in a near-linear fashion.
If it rains twice as much,
then it rains twice as much across the whole climate associated precipitation region.

These assumptions were implicit in the design of the synthetic example.

At face value *A1* seems like a onerous condition to be met.
However,
in practice this seems to be a soft requirement.
For instance in the southern Thailand at the seasonal scale we expect additional Madden Julian Oscillations (MJO) - see **SUPP**.
At the interannual scale we expect some climate patterns associate with the El Niño–Southern Oscillation (ENSO).
However,
when looking at the maps neither seem to cause visually apparent patterns in the data.
Treated these other climate phenomena as background noise has not introduced notable issues in the final result.
Furthermore,
the authors have no been able to find any locations with three or more visually distinct seasonal rain patterns.

Characteristic *A2* will be at the root of fixing the climate signal mixing issue.
It's seldom observed that many climate systems effectively form dipoles.
These can be for instance the winter and summer monsoons.
Or interannual systems like El Nino/La Nina.
There are many more such systems,
like the Indian Ocean Dipole,
the Southern Annular Mode,
the North Atlantic Oscillation as well as many others.
The key characteristics they all share is that both phases/systems can not coocur.
This will form the central crux of the method.

Assuming A1 to be generally true,
and bulding on the intuition we developed in the synthetic case,
we can then interpret the first two singular vectors as largely consisting of different mixtures of the two underlying signals.
By virtue of there being just two degrees of freedom,
a certain combination of the two SVs should give back one pattern.
Another combination should give us back the other pattern.
That means in our case study some mixtures of SV1 and SV2 should give us back the summer and winter monsoon patterns.

To simplify the problem we can reduce our problem space to two dimensions.
We can replot all our observations on to two axes.
SV1 and SV2 will form the X and Y axis respectively.
These two projections correspond to the first two columns of the left-singular-vector matrix of the SVD.
The remaining SVs describe the noise,
or variability,
in the weather.
These form the basis for estimating the error in the SV1/SV2 projections.
The error analysis is a bit tangential to the main thrust of the method,
so we have left it to the supplementary section.
Ultimately they serve to provide a very modest improvement to the correction.
They also allow us to estimate an upper bound on the error in the final result.

Looking at our data in this subspace,
we immediately see the effect of the second simplifying assumption *A2*.
The two climate systems cause the observation to arrange themselves in two clusters.
Since data is generally non-coocurring we have few points in-between.
One cluster is dominated by summer (yellow) months while the other winter (blue/purple) months.
This corresponds to our intuition.
Either atmospheric parameters are in some summer or winter monsoon-associated configuration.
Since these processes happen at synoptic scales,
much larger than the zone under observation,
there is very little time spent "in-between".
For instance the onset of the monsoon at the Southern end and Northern end of the selected region has been estimated to differ by approximately XXX days(REF???).
This stresses the need to select small regions for climate pattern extraction.
Note that there may be short transitionary phases at the regional/mesoscale.
However,
their precipitation patterns do not necessarily correspond to a mixture of the two climate systems.
Because these phases are relatively short,
for the purpose of isolating patterns they will be interpreted as part of the noise.
If one has a more sophisticated understanding of the climate systems and their transition times,
this is potentially one area where one can construct a heuristic.
However,
transition states constitute a small fraction of observations and should not distort the final analysis.
In the extreme,
such as in regions with just one active climate system,
transitions can form a false signals.

Looking at our two clusters,
we note that they are broadly centered around two lines going through the origin.
These clustering axes represent two ratios of the singular vectors.
Returning back to our synthetic example,
these ratios suggest to use the mixing ratios of the underlying climate systems.
To estimate these two ratios we use a procedure akin to Otsu's method in computer vision.
We subdivide the 2D subspace along all possible diagonal dichotomies.
We then find the dividing line which minimizes the total variance of both halves.
Such a dividing line in essence ensures both halves form a tight grouping around each half's mean.
The specifics of the averaging and the error weighting is explained in greater detail in **SUPP**

Once the optimal divisor has been selected (red dashed line),
we find the best estimate of each climate-associated ratio.
The fact that points generally lie in the direction of the centroid also suggests A3 is a safe approximation.
If stronger monsoon months lead to a change in the shape of the climate pattern then we would expect  larger off-axis changes.
Arguably the summer monsoon half does show a small off-axis trend of this sort.

With ratios in hand can now draw them to see if they correspond to what we visually observed in the original data.
Looking at the top centroid,
the months are blue/purple and correspond to the late-fall/winter months.
The pattern does indeed corresponds to what we observed in the original observations,
as well as our intuitive understanding of the climate configuration during the winter monsoon.
We see rains on the southern East Coast.

Similarly,
the bottom half consists of summer months.
The SV1 SV2 mixture associated with its centroid looks like the summer monsoons rains on the west coast.
Note how the previous artifact we saw in SV1,
with spurious rains on the East coast,
has completely vanished.
Also notice how the positive offset is also gone, and we get near-zero rain over downwind ocean sectors.

== Applications: Climate Patterns

The previous steps have given us clean non-orthogonal climate patterns.
Along the way we've made several assumptions about the climate systems being observed
(*A1,2,A3*)
However,
in our estimation the method can still be seen as general and broadly applicable.
The resulting patterns can serve as the basis for further research.
First,
the spatial distribution of the pattern itself can be of interest.
Second,
once the pattern is isolated we can look for it in future (and past) data.

The pattern shape,
as described so far,
has been interpreted as a static consequence of recurrent large scale climate phenomena.
This simplified view may subtly break down in some scenarios.
For instance long term reconfigurations in the climate arrangement (ex: wind direction) may be investigated on a case by case basis by comparing climate patterns for different periods.

Furthermore,
climate patterns,
even when static,
may serve as sources of truth for validating climate models and reanalysis datasets.
Running the method on the ERA5 dataset shows a close correspondence between IMERG patterns.
Discrepencies could be a potential avenue for future investigation

== Applications: Climate Indeces

The presence of climate associate patterns in past and future data allows us to construct climate indeces.
Many climate indeces are built on the bases of using EOF analysis - particularly the first singular vector,
EOF1.
These methods typically give plausible results due to two common phenomena.
First,
as was noted before,
most climate phenomena come in pairs.
Second,
climate phenomena have a tendency to form mirror images when viewed as anomalies from the mean.
If using one climate the wind blows east to west,
then most likely in the negative phase it blows west to east.
In our case study,
if rain patterns are normalized to the mean and you stencil out the ocean,
a very rough level the monsoons resemble negatives of each other.

Similar near-negatives can be imagined for other climate phenomena.
For instance sea surface temperatures associated with the El Nino equatorial warm water tongue vs the La Nina subtropical heating are near negatives when viewed in small boxes around the equator (REF).
The positive and negative phases of the southern annular mode,
or the north atlantic dipole also look like negatives within their respective zones of influence.

The unexpected consequence is that when working within a properly tuned region,
one may find EOF1
(which is done on an anomaly and not raw data)
produces a pattern which gives a workable one dimension estimate of both climate phenomena.
This however is not a property that is universally true
- and doesn't have any clear universal scientific rational.
For such EOF based indeces to work they need to be region-tuned and validated by other heuristics.

Our climate dipole bisection avoid the serendipity of these extra symmetry requirements.
We not only don't need to characterize the climate or construct heuristics,
but we can also look at the presence of climate in less convenient regions.
By observing climate in regional patches,
we can beging to construct a larger synoptic scale understanding of climate systems.

By treating each climate separately and generating separate patterns for me,
we can then generate two independent climate indices for each phase of the dipole.
The two pattern basis result in two indeces with non-comparable scalings.

To build the actual index we simply need to project data on to our patterns.
We use the bisecting line (red line Fig XX) to determine which climate system each observation belongs to.
The projection can either be done directly (ie. an inner product of the pattern and data) or can be done with a non orthogonal projection in the 2D singular vector subspace.
Here we once again remember that oberservation are attributable to only one climate system.
While in this representation they are shown as a mixture of SVs,
the singular vectors don't represent actual physical processes that are being mixed.
Restated,
the intensity of a climate pattern in an observation is unrelated to the other climate phase's shape.
Hence,
the former direct inner product method is likely preferrable.

For the projection's error bound estimation see SUPP.

== Conclusions and limitations

Using a synthetic example,
We started by observing the serious issues with a typical EOF analysis.
Once we identified several likely causes,
we first simplified the mathematical formulation by returning to the SVD
(with no anomaly).
We observe that the climate patterns seem preserved in a mixed state in the problematic singular vectors.
Then,
through a small set of simplifying assumptions,
we formulated a simple physically interpretable method for extracting the patterns.

In the final analysis,
we may encounter a breakdown in our simplifying assumptions.
These generally fall in to several categories:

.A breakdown in assumption *A1*
This is caused by two scenarios:

The most common issue is that you have a single climate pattern that is forceably bisected.
Such scenarios typically have certain characteristic features.
Non-linearities in onset/withdrawl are exposed,
breaking assumption *A3*,
and you get characteristic on/off/on climate index patterns.
A characteristic example is explored in SUPP

The other possible issue is tertiary climate systems.
Such systems are typically of a different magnitude from the primary climate dipole.
While such systems should be evaluated on a case by case basis,
they don't typically interfer with the estimated climate-dipole patterns.
In our case study we manage to detect the effect of the MJO by using daily observations.
See **SUPP**
However,
a holistic framework for accounting for weaker tertiary signals will be an area of future work.

.A breakdown in assumption *A2*
Will causes certain characteristic issue that are usually detectable.
There are broadly three potential causes:
 1 :: the region under observation is too large.
Climate signal onset/withdrawl across the whole of a region takes a significant amount of time.
Second,
 2 :: the observed parameter is slow to change.
The time between climate systems has an undefined shape.
 3 :: The integration time for each observation is too large.
For instance,
in the case study region,
monthly precipitation averages will result in months where both climate systems are active.

Such scenarios are usually readily observable in the SV1 SV2 plot.
The problematic observations will typically end up between the climate associate mixtures.
Such observations end up skewing the centroids to the mean.

An interesting example is explored by looking at sea surface temperatures in the South China Sea.

The issue with all three listed breakdowns is that they will likely exhibit different patterns.
We can't even safely say that transition state patterns will look like mixtures of the underlying signals.
So there is no universal turn-key way to account for these.
Climate system and region specific heuristics,
on a case by case basis,
can likely be constructed to eliminate problematic observations to improve results.

All these issues notwithstanding,
in a climate dipole region even skewed bisection patterns provide a clear improvement over the EOF basis.
The EOF basis is guaranteed to be a mixture,
and the second EOF's orthogonality constraint almost guarantees it will miss the mark.
Furthermore,
our bisection method presents a clear,
physically motivated and mathematically simple correction.
This makes it much easier to interpret and accept that more complex EOF rotation routines.

Finally,
because the method as presented has no tuning parameters or climate system specific considerations,
the resulting patterns have the impartiality and repeatability that allow it to become a concensus result that can form the start or further research.


== SUPP: Error Analysis

For the purpose of this analysis we will not be considering instrument error as this goes in to the specifics of the IMERG system and is outside the scope of the method

The error propagation will be explained in several steps:

1. We first will characterize the noise
2. Then we will explain how it affects the projections in the SV1 SV2 subspace of FIG????
3. This then will establish an error of the climate patterns themselves (FIG?? FIG??)
4. After which we can estimate the error of the climate index - ie. the projections of the time points on to the climate patterns themselves.

=== 1: The Noise

The simplifying characteristic A1 tells us that if we remove the first two singular vectors we are left with an estimate of the noise component of the system.

.De-noised data (ie. data with SV1 and SV2 removed)
image::imrg/krabi/monthly/noise-all.svg[]

The de-signaled data,
as expected,
looks like noise with no discernible climate patterns.
This remaining noise should have an expected value of zero.
Any non-zero value would in-effect indicate some additional climate signal,
which would run counter to *A1*.

The noise's variance generally increases with an increase in monsoon signal.
Visually we saw in FIG??? that the monsoon pattern manifests unevenly.
Intuitively,
we expect that when there is little signal/monsoon thing are dryer and the noise level is reduced.
When the climate signal is strong the noise level is higher.
At such times some patches may remain entirely dry,
while others may have large amounts of precipitation.

To observe this,
we can re-plot the months by their power in SV1+SV2 compared to the power of the remaining SVs (SV3,SV4,SV5,..etc).

.Signal to Noise plot
image::imrg/krabi/monthly/power-sv12-vs-other.svg[]

Unfortunately,
while there is a general linear relationship,
it isn't very robust.
There are many outliers and a lot of variability.

=== 2. Error in the 2D SV1 SV2 subspace

The noise level is important because it affects our estimates of projections.
While the expected value of the noise is zero,
the actual mean will never be exactly zero.
The variance of the measured mean is akin to the classic standard deviation of the mean (SDOM).
When you project your data on to a pattern (ex: SV1 or SV2),
the mean of the noise in areas of the pattern will be folded in to the projection.
So when calculating the inner product of the pattern and measurement,
the noise will cause you to either overestimate or underestimate the strength of your signal.

So when we took our data points and placed them on the SV1 SV2 plot (FIG????),
we had implicitly done this projection.
The noise's mean at every point in time was folded into the projections and had skewed our results.
While the size of the skew can't be know directly,
the magnitude can be estimated by knowing the variance of the noise.

For the purpose of this analysis we treat the SV1 and SV2 patterns/vectors as both having negligible errors relative to the data.

.TODO:
IS THIS A SAFE ASSUMPTION? DO I NEED TO ESTIMATE THE ERROR OF THE SV? CAN BE DONE BY DIVIDING DATASET AND CALCULATING.. OR SOME BOOTSTRAP?

We had originally gotten the projections by looking at the left singular vectors of the SVD.
However,
if done explicitly,
the projecting is done by taking the inner product of the data and the pattern.
Note that the left singular vectors are unit length,
While the projections are not.
So the final errors need to be divided by the corresponding singular value to be at the same scale
In other words we go pixel by pixel multiplying the pattern *P* with the data *D* and summing them all up:

stem:[sum_(pxl=1)^n P_{pxl}*D_{pxl}]

The pattern pixels *P* have negligible errors so we treat them as constant.
The data pixels for each time point *D* are some signal *S* with some noise *N*

stem:[sum_(pxl=1)^n P_{pxl}*(S_{pxl} +- N_{pxl)}]

We can separate this into the original inner product and the sum of zero mean errors:

stem:[sum_(pxl=1)^n P_{pxl}*S_{pxl} +  sum_(pxl=1)^n 0 +- P_{pxl}*N_{pxl}]

The best estimate of *S* is *D* so the left hand side is just our original inner product.
The error of the sum of errors is their quadrature sum.
So the final inner product will be:

stem:[sum_(pxl=1)^n P_{pxl}*S_{pxl} +- sqrt(sum_(pxl=1)^n (P_{pxl}*N_{pxl})^2)]

The last step is deciding on a value for *N*.
One option is to use the linear relation from FIG????.
However this presupposes a constant noise power across the whole field and that the noise level is purely a function of the signal strength.
Fortunately since the patterns fields are large and since we have many pixels and can directly estimate the noise level at every point in time.
If we treat each pixel as a separate random process with mean zero and unknown standard deviation then the designaled data gives us one trial.
The absolute value of the designaled pixel is our best estimate of of the standard deviation *N*.
So the error estimate is quadrature sum of the product of the designalled data and the pattern.

At this step the pattern *P* is either *SV1* or *SV2*.
The quadrature sum, after dividing by the corresponding singular value, provides the X and Y error in FIG????.
Note also that a larger pattern will make the relative noise smaller.

image::imrg/krabi/monthly/sv-projs-with-errors.svg[]

=== 3. Error in climate pattern

Now each data point in the SV1 SV2 plane has X and Y errors which we will call dX and dY.
To find the ratio of SV1 and SV2 associate with each climate pattern,
we first need to calculate the associated ratio for each data point.
If we calculate X/Y for each point then the associate error is the sum in quadrature of the fractional uncertainties:

stem:[X/Y +- sqrt(((dX)/X)^{2} + ((dY)/Y)^{2}]

.TODO:
- RATIO SEEM PROBLEMATIC AS IT EXPLODES TO HUGE VALUES AS Y GOES TO ZERO.
- MAYBE RADIANS?
- MAYBE PERCENTAGE OF SV1? (X/(X+Y))

When calculating the averages and variances of each half we now use these ratios with their associated errors.
Assume the errors are independent and normally distributed,
we can use the variances to make a weighted average and calculate a weighted variance

https://en.wikipedia.org/wiki/Inverse-variance_weighting

.TODO:
- SHOULD I ADDRESS THE INDEPENDENT/NORMAL CRITERIA..?
- OR FIND AN ELEGANT WAY TO ACKNOWLEDGE AND SKIP IT..?

When the variance minimizing divider is found,
the average will yield a ratio that corresponds to each the climate pattern.
The associated variance will specify the error in that ratio.
We can then use the error in the SV1 SV2 ratio to calculate average + error and average - error patterns and thereby calculate a pixel level standard deviation.
Naturally areas with high values in SV1 and SV2 will result in higher errors.

THE ERRORS "BARS" ARE LIKELY NOT SYMMETRIC.. NOT SURE HOW TO HANDLE/DISPLAY

.TODO:
- A MAP OR THE ERRORS FOR SUMMER AND WINTER MONSOONS??

=== 4. Error in Climate Index

The final error to be determined is the error in the final calculated climate index.
This is the projection of each time/data point on to each climate pattern.
Here the procedure is the same as when we projected on to SV1 and SV2.
However, while we treated SV1 and SV2 as having no effective error,
here we treat the climate patterns as having an error.

stem:[sum_(pxl=1)^n P_{pxl}*D_{pxl}]

So in the previous equation both P and D now have an error associated with them.

stem:[sum_(pxl=1)^n P_{pxl}*S_{pxl} +- N_{pxl}]

Here N is the quadrature sum of the fractional uncertainties.
We then proceed as before doing a quadrature sum of these combined probabilities.
This gives us the error bars on the final climate index projections.



== SUPP Pattern separation at different time scales

In our primary case study we look at precipitation totals at the pentad scale.
This integration time, or time box size, was chosen to help illustrate the method.
It gives nice separation in the SV12 subspace while avoiding the issue of longer time-boxes.

In this section we will do a quick overview of the behavior seen with larger and smaller integration times


=== Large time boxes

We first look at the issues that arise with larger time windows by looking at the same region using monthly precpitation values.
Monthly maps are provided directly by the IMERG

TODO: IMAGE OF MONTHLY SV12

What we start to see is a proportion of the higher energy (ie. further from the origin) data points lie between the two climate clusters. A large fraction of these occur during the late Fall (purple/violet) and correspond to transition points. The change from Summer Monsoon to Winter monsoon occurs rapidly in the region. The month-long time box in effect captures a certain amount of summer monsoon, indeterminate transition state, and winter monsoon. The final monthly map looks like a mixture of the two monsoon signals! This is an aliasing-type problem that runs counter to the method's built-in assumption that the climate will never coocurring.

== Small time boxes

We can also decrease the time box size. Decreasing the time step effectively provides us with more data points for a give period of time. The practical limit is a daily average - as any smaller time increment would need to contend with diurnal variability. Diurnal climate patterns are definitely present, but the separation of diurnal climate systems from seasonal (and potentially interannual) patterns is an area for future work and outside the scope of the current method. At the daily time-scale we may still observe transitional states, where neither climate system is established and hence neither pattern is present. However, we become less likely to capture actual mixing of mutliple climate systems in one integration time-step

When we observe the SV1 SV2 subspace again, we no longer see a distinct two-cluster system. At first glance it looks like all points are a mixture of the end members.

TODO: Image of daily SV12 subspace

However when we do our variance minimization method and look at the two centroids we find that the resulting patterns are identical

TODO: Daily patterns


Replotting all the data's angular component - a histogram shows that in the cloud of points you are getting two peaks. Each point is just perturbed by such a large amount of noise that the previously distinct clusters are lost. Unfortunately the variability in this subspace greatly exceeds the variability estimates in our Error Analysis, which suggests there is some room for improvement.

Looking at this spread one can't help but notice the wedge-like shape. These top and bottom edges of the wedge are not mixing end-member but in effect delimit an "allowed" zone of SV1 SV2 mixtures. Note how SV2 has large positive and negative values. Projections outside these zones would represent in mixtures that result in large negative zones in these SV1, SV2 component sums. Since precipitation must always be positive, the remaining noise would need to "fill in" these negative zones - which becomes increasingly unlikely as the zone becomes larger.

Looking at the resulting climate index we can oberserve the monsoons at the daily scale with with effectively a lot of noise. Some days in the middle of the summer are classified as winter monsoon days and vice versa. Since we don't have a good characterization of the variability we leave providing a comprehensive methodology for interpreting misclassified days as an area for future work. Re-interpreting the data in pentads or other time slices at the climate index level could potentially provide resolve this issue, but would require some criteria of a new integration window. If you know the there is one climate transition per year (ex: summer to winter monsoon) one could potentially tailor a statistical method to detect this transition point

In short, smaller time steps do not hurt the climate pattern extraction process, but may create an extremely high resolution noisy climate index that is challenging to interpret.

== SUPP Rift Valley: Non cyclical signals

Unlike many EOF enhancements, the methodology as currently illustrated does not make any assumptions about climate variability over time. There are no assumptions that one climate follows another or that they occur at similar times of the year/day. This allows us to look at some more unusual climate phenomena such as the rain patters of the Rift Valley in Eastern Africa

TODO: All (monthly?) data

Here there are two rain-associated climate systems which in Ethiopia as called the Belg and the Kiremt

https://agupubs.onlinelibrary.wiley.com/doi/full/10.1002/2016RG000544

TODO: Read this thing..

While boreal summer Kiremt rains come at a consistent time every year, Belg "short" rains as a lot less consistent and associated . However the illutrated method has no issue extracting these patterns.

TODO: SV12 projs

TODO: Patterns

TOOO: Climate index


== SUPP: Sahel Mountain (Marrah): Method used in a one signal region
Maybe the most common instance would be the one monsoon-related rainy season.
At the seasonal scale,
these climate systems are may be more the norm than the exception.
In these degenerate cases SV1 will be giving you a good approximation of the climate related pattern.
No extra steps are needed.
Unfortunately,
at the moment there is no clear statistical method identifying which regions have climate dipoles.
An ad hoc method is looking at the singular values in a scree plot.
However,
there is no clear line between a two climate system and one where characteristic *A3* have broken down.
Non linearities in climate associated patterns may cause Onset/withdrawal periods to present patterns distinct from the main climate associated period.
For an example of this phenomena see the Marrah Plateau in **SUPP**
Such situations need to be identified by the researcher on a case-by-case basis.


It must be noted that globally, most locations do not feature a bistable climate. The most common scenario is a simple one-system precipitation climate (at the seasonal scale). In these locations no tricks are necessary. The first singular vector (or first EOF) will extract the single pattern.

So it is interesting to try to observe what occurs if we apply your method in these situations. As a case study we look at the Marrah mountains in southern Sudan. This massif lies at the edge of the Sahel and is subject to a single monsoon-driven rainy season. The massif's topography has some interplay with the monsoon related atmospheric configuration which drives the dominant precipitation pattern.

TODO: SV12 plot

First note that we no longer see a clear separation in the SV12 subspace. The data presents an even spread across the allowable wedge. The two extracted patterns no longer have a clear physical interpretations

TODO: Pattern 1 &2

But when we look at the resulting climate pattern we do see a consistent pattern

TODO: Climate index

The single pattern is being torn apart in to a monsoon signal and an onset/withdrawl pattern. Remember that one of the assumptions of the EOF  (A3) was that:
" The climate patterns in question scale in a near-linear fashion.
If it rains twice as much,
then it rains twice as much across the whole climate associated precipitation region"

Here we see this assumption fall apart as the weaker onset/withdrawl monsoon takes on a warped shaped as compared to the middle of the rainy season.
This onset/withdrawl false pattern occurs regularly when the method is applied in single-system regions and is a good indicator that the method should skipped in favor of simply using the first singular vector (or first EOF1).

A look at the singular values confirms also gives us a strong indication there is effectively no second climate system at the seasonal scale

== SUPP Diurnal cycles: Maritime continent
So far we have limited ourselves to seasonal climate systems. However the method may work at other time scales. Here we present a quick examination of the diurnal cycle off the coast of Java for the period (TODO Specify period):

TODO: Data image

Again IMERG can be used as it provides extremely high resolution data at the half hour interval

TODO: SV12 plot

We again get some separation ..

A lot of intermediary state

Very noisy input

But it kinda works..
And you can have a lot more input data

Watch out for seasonal signals.
Separation of signals at different time scales is outside the scope of the paper



== SUPP Korean Peninsula: Large Region vs Small Region

We noted in passing that working at the mesoscale allows us to get clear climate onset/withdrawl.
Here we present results when a region that is too large is used.
We look at the Korean Peninsular at two different scales

Things go bad


== SUPP: Notes on IMERG

For the Southern Thailand case study we selected to use the V06B Late data provided by IMERG (in GeoTIFF format). We find that other versions produce notable issues related to a "climatological adjustment" made using GPCC gauge data. This rain gauge correction was added to the "Final" version of version V06B. In version V07B the correction is incorporated in both Late and Final version. The Early version is still unaffected, however it "only has forward propagation (which basically amounts to extrapolation forward in time), while the Late has both forward and backward propagation (allowing interpolation)". See: https://gpm.nasa.gov/data/imerg FAQ Section.

The adjustment creates a notable stenciling effect. The stencil seems to reflect the GPCC stencil seen in GPCC precipitation maps:
https://climatedataguide.ucar.edu/climate-data/gpcc-global-precipitation-climatology-centre

Here is an example using v7 monthly data:

TODO add images

V06 is provided in several different subversion. One is labeled V06B and GeoTIFF files are provided through 2022-05-07. The next next period goes through multiple version through 2024-06-02. To avoid any discontinuities in the analysis. We look at v06B data exclusively on the 2011-01-01 to 2020-12-31 (inclusive) period.

To simplify the analysis and create even annual cycles we subdivide the 365 day calandar year into pentads by removing all occurances of the leap day - February 29th.



== Long Abstract

=== V1

The interplay between recurring atmospheric processes and local topography creates regular observable climatic phenomena.
We present a novel method for analyzing the spatial distribution of atmospheric parameters at the mesoscale,
which will allows for the extraction of a pair of underlying climate-associated shapes.
The method builds on the singular value decomposition (SVD) and corrects for several deficiencies of a typical empirical orthogonal function (EOF) analysis.
The extracted shapes act as unique fingerprints that allow one to observe climate without having to characterize it,
without needing to understand any of its dynamics,
and without building any heuristics or adjusting tuning parameters.
Key to making the EOF correction is recognizing that a large fraction of climate phenomena come in non-coocurring pairs.
Systems such as the Summer/Winter Monsoons,
El Nino / La Nina and the positive and negative phases of many climate systems are all typically in one of two modes.
In effect the presence of one climate state precludes the occurrence of the other.
As a result of this bistability,
when using the SVD to reduce the measured climate parameters to two dimensions we observe clustering around two linear combinations of the basis vectors.
These two combinations can be found using a variance minimizing search (Otsu's method) that terminates at an optimal solution and represent a simple mixture of the first two singular vectors.
The mixtures' associated shapes can then be used to measure the presence of the climate phenomena in the original data to build a rolling two state climate index.
We present several examples using the IMERG precipitation dataset,
the ERA5 precipitations model estimates and a small synthetic data example.
An accompanying program for reproducing the analysis is provided.


=== V2

Many climate phenomena historically aquire names by a process of pattern-matching by local observers.
In simple terms,
large scale climate conditions are observed to cause a higher likelyhood of some corresponding weather.
While the naming of phenomena is useful,
due to the inherant variability,
local weather observation are never sufficient for inferring the current climate state.
However,
by observing weather across a region,
(ie. many locales simultaneously)
we can start to make stronger inferrence about the prevailing large scale climate conditions.
The climate's statistically significant effect on the weather is complex and region specific.
Without characterizing any of the dynamics,
we can safely assume it will almost certainly be spatially irregular.
This will be due to some complex interplay between atmospheric parameters and the local topography.
Here we present a novel method for analyzing the spatial distribution of weather at the mesoscale.
By looking at weather over a given region we can extract each climate's associate associate patterns.
Then using the extracted spatial patterns we can reanalyze our weather's conformance to the pattern.
Thus allowing us to infer the prevailing climate conditions for a given point in time.
The method builds on the singular value decomposition (SVD).
We remove the need for working off of an anomaly -
as is seen in a typical empirical orthogonal function (EOF) analysis.
More importantly,
we find a way to resolve the EOFs orthogonality constraint.
Key to the new approach is recognizing that many climate phenomena come in non-coocurring pairs.
Systems such as the Summer/Winter Monsoons,
El Nino / La Nina as well as the positive and negative phases of many other climate dipoles.
The critical characteristic of a climate dipole is that the presence of one climate state precludes the occurrence of the other.
As a result of this bistability,
when the the measured climate parameters are reduced to two dimensions by SVD,
we observe clustering around two linear combinations of the basis vectors.
These two combinations can be isolated using a variance minimizing search (Otsu's method) that terminates at an optimal solution and represent a simple mixture of the first two singular vectors.
The mixtures can then be used to form the basis of a two state climate index.
We present several examples using the IMERG precipitation dataset,
the ERA5 precipitations model estimates and a small synthetic data example.
An accompanying program for reproducing the analysis is provided.


