:docinfo: shared
:imagesdir: ../fig/
:!webfonts:
:stylesheet: ../web/adoc.css
:table-caption!:
:reproducible:
:nofooter:

= Paper1
= Fixing the EOF by Climate Dipole Bifurcation
George Kontsevich

== Abstract

Large scale climate processes,
in their interplay with topography,
leave distinct fingerprints on the spatial distribution of regional weather.
If these spatial patterns were to be properly isolated,
an observer of the weather would be able to infer which climate system was active at any given time.
Building on the singular value decomposition (SVD),
we present a method for estimating these climate-associated patterns.
Mirroring the method of empirical orthogonal functions (EOF),
eshewing tuning parameters and heuristics ensures an impartial method that is region agnostic.
Key is recognizing that many dominant climate phenomena come in non-coocurring pairs.
When reduced to two dimensions by SVD,
weather records align around two linear combinations based on which climate dipole phase is active.
These combinations,
once isolated,
form the basis of regional two-state climate indices.
We present an example using the IMERG precipitation dataset,
along with software for reproducing the results.


WORD LIMIT: 150
WORDS: 149

== Introduction

Climate systems,
such at the monsoons or El Nino/La Nina,
acquired their names when people native to a region noted recurring weather phenomena.
By constract,
a typical modern approach for identifying climate system involves searching for and then characterizing repeated atmospheric configurations.
Nonetheless,
when climates are poorly understood or are still not well characterized,
the original methodology of pattern recognition comes naturally to the untrained eye.
While at times imperfect,
it presents a simple method that can be used regardless of location.
Pattern recognition,
as applied in the atmospheric sciences and oceanography,
has been typically done using empirical orthogonal function
(EOF)
analysis.
This is typically shorthand for a singular value decomposition
(SVD)
of some parameter's anomaly from a mean.
The resulting patterns,
(EOF1 EOF2 EOF3 etc.)
are meant to roughly represent the patterns that repeat in the weather observations.

The quality of the resulting EOF patterns is generally inconsistent,
as a result they are often viewed with a degree of skepticism;
Notwithstanding the issues,
they still often find use as a starting point for further quantitative analysis.

As will be explored,
the fundamental issues affecting EOFs are:

O1:: EOF patterns are orthogonal,
climate-associated patterns are generally not.
O2:: All EOF patterns,
including EOF1,
represent mixtures of all the underlying signals.
O3:: EOF1 will often be heavily biased towards the dominant climate signal -
often giving a false sense of reliability.

The fact that the EOF is built on the anomaly
(from some mean),
while a seemingly sensible starting point,
is in fact another source of hard-to-resolve issues.
The root cause is that,
in the presence of multiple climate systems,
mean structure does not typically correspond to a physically meaningful process.
Worse yet,
any such mean must contain a mixture of all the climate patterns that have been observed.
As a direct consequence,
when converting raw observations to anomalies,
one in-effect takes every observations and subtracted some static mixture of every climate signal
(and this mixing ratio is typically unknown).
Meanwhile,
the original observations have one or another climate associated pattern;
and these patterns are non-static - varying in intensity over time.
Operating on the anomalies means one now has to disentangle mean-derived constant patterns,
and the patterns of the original observations.
This needlessly complicates the pattern extractions process.

To sidestep this problem,
we confine ourselves to the using the SVD on original observations directly.
This means that instead of EOF1, EOF2, .. etc. we will use the singular vectors SV1 SV2 .. etc.

All the aforelisted issues (O1..4) hold just as well for the SVD as for the EOF.

Our objectives are:
first,
to conclusively illustrate the problems with the EOF1;
second,
to presenting a simple method for resolving them.

== Materials

- We first illustrate the aformentioned issues with EOF-like analyses using synthetic data.
While the synthetic weather model will be extremely basic,
it will to allow us to know a-priori which climate patterns are present.
When we try to extract patterns,
using the SVD,
we can observe discrepencies with the originals we have in hand.
Once we see the issues that occur,
we can identify the causes and start considering how we may resolve them.

- For a case study we look at precipitation over Peninsular Southern Thailand.
The region was chosen because of ongoing paleoclimatological work in the area. *REF*
The top of the Malay Peninsula is climatologically challenging.
It is subject to two distinct monsoon systems:
The dominant monsoon system is the so-called summer monsoon
(ie. boreal summer).
It brings moisture from the Indian Ocean and Andaman Sea.
The secondary system is the winter monsoon,
which primarily brings moisture from the East - the South China Sea and the Gulf of Thailand.

- To help us demonstrate an improvement over the EOF/SVD,
we test the method using gridded precipitation data.
For this we will use the "IMERG Late" dataset.
(**SUPP** Notes on IMERG)
In terms of pattern extraction,
we don't observe any sensitivity with regard to time bin size,
with daily to monthly bin sizes all producing near-identical climate patterns.
Nonetheless,
for the sake of visual clarity,
we present daily accumulations binned to pentads
(with leap days removed).
An equivalent analysis using daily data is provided in **SUPP**
IMERG has a 0.1x0.1 degree resolution.
This gives ample room to select small regions of interest.
As will be discussed,
operating on small regions directly benefits pattern extraction.

.Supplementary sections explore:
The Great Rift Valley:: A region with semi non seasonal climate signals.
Marrah Mountains (Sudan):: A region with one climate phenomena and the breakdown in one of the EOF assumptions.
Java Island:: Diurnal cycles with large errors and less stationary patterns
ERA5 reanalysis precipitation:: The method as used to validate climate model output
IMERG Final Result:: Showing artifacts caused by numerical normalization procedures


== Synthetic illustrations of the EOF/SVD problem

Using a synthetic dataset allows us to not only observe the aformentioned problems (O1 O2 O3),
but it will also give us insight in to a possible solution.
We start by creating two arbitrary patterns,
representing the two states of our climate system.
Since the pattern were chosen at random they will not be orthogonal to each other
(anticipating issue *O1*).
The patterns are then perturbed to create synthetic "observations".
For ease of interpretability,
the observations are arranged to mimick monthly precipitation accumulations of a monsoonal region.
First there are several summer-equivalent patterned observations.
This is followed by a shorter period of winter-equivalent patterned observations.

When we look at the first two singular vectors (SV) generated by the SVD,
the first thing that stands out are the negative values in the first singular vector (SV1).
These values,
colored in blue,
are characteristic of most SVD numerical routines. **REF** North?
Most such routines,
such as the Intel MKL library used here,
when run on purely positive observation such as rain,
will return negative values for the first singular vector.
In practical terms this does not turn out to be meaningful.
As a basis vector the sign could be safely inverted;
one would just need to invert all subsequent weight values.
Since it would be of no practical benefit,
we keep the singular vectors unaltered.

The next thing we notice are the mixed signals.
As we had stated in *O2*,
the SVD's singular vectors all end up looking like a mixtures of our original patterns.
For many climatologists it may come as a surprise that the first basis
(equivalent to EOF1)
has also been affected.
This mixing is a direct consequence of how the SVD is designed to extracts patterns.

.The SVD as an iterative algorithm
At a high level,
the SVD algorithm can be viewed as an iterative algorithm;
building singular vectors one after another.
Once a singular vector is created it is removed from the observations.
These new adjusted observations are then used to make the subsequent SV.
Note that "removing a singular vector" means removing any component in the same direction
(such that the inner product becomes zero).
As a result,
all the adjusted observations end up orthogonal to that SV.
When the next singular vector is built from these adjusted observations it too will be orthogonal.
This is because singular vectors are constructed by a linear combination of the observations
- so if all the adjusted observations are orthogonal,
then so will their combination.
This tells us that issue *O1* is a direct result of the algorithm's design.

.Singular Vector construction
To understand why the singular vectors
(even the first one)
end up mixing signal
(issue *O2*)
we need to understand what the SVD does at each iteration.
When building a singular vector,
for instance when building SV1,
the SVD is fundamentally doing a weighted average
(ie. linear combination)
of the data/observations.
The weighting is said to maximizes the induced matrix norm.
In other words,
the weights are selected such that the euclidean length
(2-norm)
of the resulting singular vector is as large as possible.
When looking at the singular vectors as pattern images
(as illustrated),
the euclidean length is effectively the sum of the squares of all the pixels.
The squaring in effect drives the pattern extraction.
A straight sum
(the manhattan 1-norm)
would cause the algorithm to simply add observations with the most rain
(or whatever parameter one is using).
However,
the squaring drives the algorithm to favor vectors that maybe have a smaller direct sum,
as long as certain pixels have extra large values.
This is because a large value will have an even larger squares;
This drives up the euclidean length.
In fact,
it's likely typically the euclidean length is largely a function of these large values.
If you want the square of the pixel-values to add up to a maximal value,
then at face value it seems one should add-up similar images
(ie. some repeating patterns)
so that pixels "added up" together;
even if the actually pattern area is relatively small.

However,
this mathematical interpretation does not correspond to what we see in the result.
What we actually see is that the singular vectors have multiple patterns at once;
seemingly counter to the maximization objective.
The root cause is a subtly of an algorithmic constraint we have elided.
When the SVD is maximizing this weighted average of the observations the weights must have been implicitely limited somehow
(so that the SVD can not pick arbitrarily large weights).
The limit is that the weights must be of unit length.
In other words,
the sum of the squares of all the weights must equal to `1.0`.
As previously,
the squaring makes a subtle but important difference
(here breaking the pattern extraction instead of enabling it).
As before,
while the sum of squares is a constant `1.0`,
the direct "normal" sum of weights is not constant.
All else being equal,
spreading weights out actually makes their sum a higher value.
This is most easily illustrated by looking at the logical extremes.
If all weight was assigned to just one observation
(for instance the one with the most total rain)
and all other weights were set to zero,
then the sum of weights would equal `1.0`
(same as the sum of squares).
By contrast,
an even spread of weights across all `N` observation would give each weight the size `1/sqrt(N)`.
Here the sum of squares still equals `1.0` for all values of `N` (the constraint is satisfied).
However,
the direct sum is now `N/sqrt(N)`.
Since `N/sqrt(N) > 1.0` for all values of `N`>`1`,
this tells us that the algorithm will have a tendency to spread weights,
to increase the weight-factors and thereby increase the euclidean length of the sum.
As a result,
while observations that exhibit the dominant pattern do get higher weights
(to maximize the high-value pixels),
the observations with secondary signals will also get small weights assigned to them
(to maximize the sum of the weights).

The end result is our SV1 vector ends up looking like a mixture of both underlying signals;
highlighting our issue *O2*.
While testing,
we have tried adjusting the ratio of the two climate pattern in the synthetic data.
We observe the mixing effect diminishes rapidly as the difference between climate signals increases;
which points us to issue *O3*.
However,
the mixing ratio is not something we have any analytic insight into,
hence we don't explore this thread further.

The next and perhaps even more glaring issue is the second Singular Vector (SV2).
As we just determined,
SV1 is some unknown mixture of the two patterns.
Before SV2 was constructed,
this mixture of patterns was removed from the observations.
As a result,
the adjusted observations
(which are no longer purely positive)
all had some component of both signals.
We can already speculate that a pure climate signal will not be extracted.
The maximization procedure still proceeds,
but because these adjusted observations were made orthogonal to the first mixture,
the possible outputs are constrained.
What is interesting is that the maximization ends up returning a different mixture of the two original patterns;
with some negative and positive regions.

After the second singular vector is removed,
the remaining re-adjust observations have had all their patterns removed.
Hence all subsequent SV have no patterns present.
While we don't provide a rigorous proof,
the result comes naturally when viewing the degrees of freedom of the system.
The original two signals provided two degrees of freedom in our observations.
By removing the projections of two arbitrary signal-mixtures we must remove both signals from all the obervations.

The final result,
the first two SVs being different mixtures of the underlying signals,
ends up being the critical piece that will allow us to build a correction.

== Case Study: South East Asian monsoon systems

We now repeat the same analysis on a real-world example in southern Thailand.
Here we do not have a priori knowledge of the climate associate patterns.
However,
we do have a some high level understanding of the climate configuration.
This should be sufficient to confirm the SVD/EOF problem.
Once confirmed,
we can construct a easily interpretable correction.
This will produce patterns with a much higher fidelity to those we observe in the raw data.

A preliminary visual inspection of the weather shows us that there are two distinct patterns.
The summer months have rain on the west coast,
predominantly in the northern-most part of the region.
The late fall and early winter months show rain in the south-eastern section.
These two rain patterns correspond to summer and winter monsoon systems.
At a high level,
the patterns are the result of a complex interplay between the local topography and the seasonal synoptic scale atmospheric conditions.
In this particular case,
the areas with the highest rainfall correspond to coastal mountains downwind of their corresponding monsoonal systems.

As in the synthetic example,
we first try to extract the underlying patterns by SVD.
The first singular vector gives us a shape that looks encouraging.
The shape at face value seems similar to the west coast precipitation associate with the summer monsoon.
Often an EOF anaylsis would stop at this point as the result doesn't have obvious glaring issues.
While our synethetic example showed that mixing must be happening due to issue *O2*,
it is not immediately apparent in this image due to a couple of reasons:

- First,
unlike in the more balanced synthetic example,
here summer monsoon rains form a dominant fraction of the annual total.
Issue *O3* strongly preserves the pattern.
- Second,
unlike our synthetic patterns,
natural patterns are typically smooth.
As a result,
their mixtures do not have large obvious artifacts.
Here only a careful eye will note the issue.
When looking at the first singular vector,
we see a small intensification of precipitation on the East coast which is not apparent in summer months.
The error in the pattern only becomes easy to detect once we have the corrected patterns for a side-by-side comparison.

The second singular vector,
orthogonal to the first,
shows some very strong east west contrast with both positive and negative values.
Not only does this not look like either climate system,
since we aren't working off an anomaly
(like in an EOF analysis)
the climate-associated patterns of precipitation should be positive.
Inverting the vector's values doesn't solve the issue;
as it would just creates other negative zones.

== Isolating correct patterns by SV subspace bisection

We already know,
from our synthetic example,
that the root cause of the observed problems with the singular vectors stem from them representing mixtures of the underlying climate signals (*O2*).

Unless you are in a region with a single dominant climate system,
the singular vectors can not be safely used directly.
Unfortunately there is no simple way to differentiate single climate regions from multi-climate ones.
Such situations need to be identified by the researcher on a case-by-case basis.
For an indepth look at the common indicators of single system regions as well as associated challenges,
please see the Marrah Plateau example in **SUPP**

To isolate the climate systems we need to assume three simplifying characteristics:

A1:: the local climate system can be approximation as a noise dominated system of two signals.

A2:: these two climate systems by-in-large don't undergo any mixing.
In other words the two climates do not coocur.

A3:: The climate associated weather patterns scale in a near-linear fashion.
If it rains twice as much,
then it rains twice as much across the whole climate associated precipitation region.

These assumptions were in-fact implicit in the design of the synthetic example.

The critical reader will likely start to see situations where these simplifying characteristics do not hold.
Discussion of what happens when these assumptions break down is deferred till the end.
For the moment we will treat them as good approximations.

Characteristic *A2* will be at the root of fixing the SVD's climate signal mixing.
It is not noted often enough that many climate systems form dipoles.
This describes not only the winter and summer monsoons,
but also interannual systems such as El Nino/La Nina.
There are many more such systems,
such as the Indian Ocean Dipole,
the Madden Julian Oscillations,
the Southern Annular Mode,
the North Atlantic Oscillation as well as many others.
The key characteristics they all share is that both phases/systems do not coocur.

Assuming *A1* to be generally true,
and building on the intuition we developed in the synthetic case,
we can then interpret the first two singular vectors as each making an estimate of some unique mixtures of the two underlying signals.
By virtue of there being just two degrees of freedom,
a certain combination of the two SVs should give back one pattern,
while a different combination should give us back the other one.
In other words,
in our case study,
mixing SV1 and SV2 should give us back summer and winter monsoon patterns.

.Dimension reduction
To search for the mixtures we first simplify the problem.
We reduce our problem space to two dimensions.
This entails replotting all our observations on to two axes;
SV1 and SV2 forming the X and Y axis respectively.
We could take the inner product of every observation with SV1 and SV2 and then plot.
In reality,
this projections are always calculate when building the singular vectors.
They will correspond to the first two columns of the SVD's left-singular-vector matrix.

The remaining discarded SVs
(SV3 SV4 ..)
can actually tell us a lot about the variability in the climate associate patterns.
This noise-like factor can then be used to estimate the errors in the SV1/SV2 projections.
While the error analysis is technically interesting,
it is tangential to the main thrust of the method.
We have left it to the supplementary section. **SUP**

Looking at our observations in this reduced 2D subspace
(Fig 2),
we can immediately see the effect of the second simplifying assumption *A2*.
The climate dipole causes observations to form along two lines through the origin.
One grouping is dominated by summer (yellow) pentads while the other winter (blue/purple) pentads.
The two vectors,
along which the observations are aligning,
can also be seen as a representing a ratio of the singular vectors.
As we expect,
the vector containing the summer pentads lies close to SV1.
This corresponds to the dominant climate system.
SV1 was "summer-like" and hence the projections of summer pentads lie close to this axis.
By contrast the winter vector is off-axis.

We saw in the synthetic example that the SVs were mixtures of the climates.
Now we are seeing the inverse process;
the ratios of SV1 and SV2 that represent the alignment vector will serve to "unmix" the singular vectors and recover the patterns.

.Mixing ratio estimation
To find these vectors,
and their associated ratios,
we use a procedure akin to Otsu's method in computer vision.
We first subdivide the 2D subspace along all possible diagonal dichotomies.
In a 2D space the number of angular dichotomies increases linearly with the number of observations.
This allows the problem to remain solvable as the numbers of observations increases
(as compared to dichotomies in higher dimensions).
We then find which of these bisecting lines minimizes the total variance of both halves; ensuring that both halves form two tight groupings.
The specifics of the averaging and the error weighting is explained in greater detail in **SUPP**
Once the optimal bisector/dichotomy has been selected
(red dashed line),
we get out the two climate-associated ratios
(dashed line).

The fact that observations lie along these ratio vectors strongly suggests that *A3* was a safe approximation.
Imagining a scenario with a breakdown in *A3*,
we would expect different climate-associated patterns between strong and weak monsoon periods
(the monsoon strength is indicated by the distance from the origin).
In such a scenario it would be very unlikely a static SV1 SV2 ratio could adequately describe both patterns.
The ratio would change in a consistent way based on the climate strength.
Looking at the SV1/SV2 plot of such a region,
one would expect the climate grouping to drift off-axis as observations were further from the origin.
Arguably in our case study the summer monsoon half does show a small off-axis trend.

With ratios in hand,
we can now draw them to see if they correspond to what we visually observed in the original data.
Both top and bottom ratios seem to closely correspond to the patterns we visually observed.
The winter months show rains on the South-East coast.
The summer months show rains on the North-West coast.
Note how the previous artifact we saw in SV1,
with spurious rains on the East coast,
has completely vanished.
Also notice how the positive offset is also gone.
We now get near-zero rain over downwind ocean sectors.

== Applications: Climate Patterns

The resulting patterns can serve as the basis for further research.

The pattern shape,
as described so far,
has been interpreted as a static consequence of recurrent large scale climate phenomena.
This simplified view may subtly break down in some scenarios.
For instance long term reconfigurations in the climate arrangement
(ex: wind direction)
could be investigated by comparing subtle changed in climate patterns over different periods.

Furthermore,
climate patterns,
even when static,
can serve as sources of truth for validating climate models and reanalysis datasets.
Running the method on the same region with the ERA5 dataset shows a close correspondence to the IMERG patterns. **SUPP**
Discrepencies,
if found,
could be a potential avenue for further investigation.

== Applications: Climate Indeces

Coming back to our original thesis.
Maybe more importantly,
these patterns allow us to objectively estimate the presence of climate in past and future observation.
Many modern climate indices are built on the EOF
- particularly using the first singular vector,
EOF1. **REF**
These indices are also typically built over climate dipoles,
with the index having both positive and negative phases.
However,
it is only because of careful tuning that one EOF vector is able to describe both phases.
Climate phenomena,
when viewed as anomalies from a mean,
have a tendency to form near-mirror images.
If one climate phase causes the wind to blow East to West,
then most likely its negative phase blows West to East.
In our case study,
if rain patterns were normalized to a mean and you stenciled out the ocean,
the monsoons would very roughly resemble negatives of each other -
with an east/west north/south symmetry.

Similar near-negatives can be imagined for other climate phenomena.
For instance sea surface temperatures associated with ENSO;
the El Nino equatorial warm water tongue vs. the La Nina subtropical heating.
These two systems look like near negatives
- especially when viewed though carefully tuned boxes around the equator. **REF**
The positive and negative phases of the southern annular mode,
or the north atlantic dipole also look like negatives within their respective zones of influence.

As a consequence,
when working within a properly tuned region,
one may find EOF1
(which is done on an anomaly and not raw data)
produces a pattern which gives a workable estimate of both climate phenomena.
However,
this is not a property that is universally true
- nor does it have any clear universal physical basis.
Such EOF based indeces require validation by other heuristics.

Our climate dipole bisection avoids the serendipity of these extra symmetry requirements.
We not only don't need to characterize the climate or construct heuristics,
but we can also look at the presence of climate dipoles in less convenient regions.
This opens the door to potentially observe climate through many simultaneous regional patches;
allowing one to construct a synoptic scale understanding of climate systems.

To build an actual index we simply need to project data on to our patterns.
We use the bisecting line (red line Fig 2) to determine which climate system each observation belongs to.
The projection can either be done directly (ie. an inner product of the pattern and data) or can be done with a non orthogonal projection in the 2D singular vector subspace.
While in our dimension-reduced 2D view observations are shown as a mixtures of SVs,
neither the singular vectors,
nor the climate pattern themselves,
represent actual physical processes that are being mixed.
The variability in the plot is only attributable to noise before the dimension reduction.
Hence the final climate mixtures don't function as actual basis vectors.
Restated,
the intensity of a climate pattern in an observation is unrelated to the other climate phase's shape.
As a result,
the former direct inner product method is likely preferrable.

For the projection's error bound estimation see **SUPP**.

It's important to note that the two resulting climate indeces are not comparable.
Unlike a tuned EOF1 region which operates with one pattern,
here we have two separate patterns that are being projected on.
As a result,
it's important to remember that we can not make statements such as
"This year's summer monsoon was 20% stronger than the winter monsoon".
EOF1 based climate indices implicitly make such a comparison possible,
but the conclusions are likely erroneous and highly dependent on your tuned region.
When operating with two separate patterns such comparisons become explicitly not possible.

== Conclusions and limitations

Using a synthetic example,
we started with a typical EOF-like analysis and observed the resulting issues.
We simplified the mathematical formulation;
skipping the anomaly calculation and return to an SVD of unaltered observations.
We concluded that the problematic singular vectors seemed to preserve the climate patterns in a mixed state.
Then,
through a set of simplifying assumptions,
we formulated a simple physically interpretable method for extracting the patterns back out.

The main points of failure worth discussion center mainly around breakdowns in our simplifying assumptions:

.A breakdown in assumption *A1*
This is caused by two scenarios:

As we mentioned at the start,
the most common climate scenario is the single climate pattern that is forceably bisected.
An example of such a scenario is explored further in **SUPP**

The other possible issue is tertiary climate systems.
In fact the given case study has several such systems.
There is the short-period MJO system,
as well as the interannual ENSO.
Tertiary systems,
as compared to the primary climate dipole,
are typically of a different order of magnitude,
and therefore do not substantially skew climate-associate patterns.
We do naturally suggest a degree of caution,
and such systems should be evaluated on a case by case basis.
However,
we have not been able to identify any region where such tertiary systems are very distinct.
In our case study,
through a careful analysis of daily precipitation,
we do manage to detect the effects of the MJO.
See **SUPP**
However,
the affected observations not only constitute a small minority,
but they also have very little energy.
(and hence are unlikely to skew the weights during the SV construction).
While we do not present any concrete evidence,
we do not think it has had an observable impact on the resulting patterns.
A holistic framework for accounting for weaker tertiary signals will be an area of future work.

.A breakdown in assumption *A2*
A certain degree of breakdown in this assumption is expected in all datasets.
The severity needs to be assessed on a case-by-case basis.
There are broadly three categories:

 1 :: the region under observation is too large.
For instance,
a region's southern section may be under a monsoonal regime, while the northern section has not yet been affected.
This causes energy to "leak" into lower power modes.
The leakage should be apparent in the singular value scree plot.
This issue stresses the need for high density mesoscale data,
such as the IMERG dataset,
and selecting regions that are as small as practical.
A region's minimum size is dictated by two factors:
The topography and it's ability to drive distinct patterns in each phase of the dipole.
The lower value between "number of observation" and "number of points/pixels" dictates the total number of singular vectors.
This may affect the ability to segregate signal from noise. (A BIT UNCLEAR WHY.. TO THINK ABOUT MORE..)
 2 :: the observed parameter is slow to change.
For instance,
when looking at a monsoonal region,
one typically sees a period of wind reversal.
Even if this has some associate patterns in the weather,
they will be typically hard to define.
 3 :: The integration time for each observation is too large.
If we perform this method on monthly precipitation averages we will often find months where both climate systems are active.

The third scenario will cause an observation that has a mixture of the two climate dipoles.
The resulting observation will lie between the two climate associate vectors in the SV1/SV2 subspace.
On the other hand,
The first two scenarios will have transition-associated patterns of an unpredictable shape.
Experience tells us that they too will typically lie between the two vectors.
While this is not a mathematically constraint,
we have not observed any system where the transition states lie outside the dipole wedge.
We find that areas outside of the wedge often having "forbidden ratios".
In the case of precipitation,
these mixing ratios cause patterns with negative values.
Hence even extremely noisy observations map to a limited wedge and never project outside.

For a simple case of we look sea surface temperature in the South China Sea in **SUPP**
Here,
as the temperature transitions slowly between seasons,
the majority of observations are within the wedge.
The seasonal end-points,
where the climate-associated patterns are fixed,
are visible but we have no objective way to extract them.

A large enough breakdown in assumption *A2*,
such as in the South China Sea example,
will end up severely skewing the estimates of the ratio axis.
When the transition states are between the two dipole states,
the skewing will make the two derived climate patterns closer to their average.

We do not present any universal turn-key way to label transitional or mixed observations.
In most cases such observations constitute a small fraction of the total,
and therefore have a minimal impact on the result.
Issues can be minimized with a good estimate of the instantaneous errors.
Transition states map poorly to the 2D subspace and these errors can be inferred from the noise/error vectors
See: **SUPP**
On a case by case basis one may wish to build region specific heuristics.
If one has special insight in to climate transitions
(ex: there is some a priori knowledge that seasonal transitions happen twice a year)
then one may try to find criteria for removing problematic observations from the SVD.
We have not found such heuristics necessary,
and caution they may mask other issues.
By looking at the SV1/SV2 plot,
it seems evident that even in the ideal case,
an adjustment of the mixing ratio would at best give an very modest improvement to the final patterns.

All these issues notwithstanding,
in a climate dipole region even skewed bisection patterns provide an improvement over the EOF vectors.
The EOF basis is guaranteed to be an incorrect mixture,
and the second EOF's orthogonality constraint almost guarantees it will miss the mark.
Climate dipole bisection presents a clear,
physically motivated and mathematically simple correction.
There are many alternate methods for trying to correct the EOF.
These are broadly called "EOF rotations",
and typically try to use SVD rotation methods from applied mathematics on the EOF.
Not only do they persist in using the EOF anomaly,
but they end up using methods that were designed with a much more complex signal-mixing problem in mind.
Signal mixing,
also sometimes called the "cocktail problem",
is a more common scenario in the sciences more widely.
Hence it has taken the bulk of the attention from applied mathematicians.
Here the SVD is used for such things are denoising.
Special methods like Independent Component Analysis leverage statistical properties of the signals to estimate the original "unmixed" signals.
However,
climate associate patterns sit in a special simpler subset of pattern extraction problems.
As we've hopefully illustrated,
once we assume a very minimal set of properties,
the non-cooccurance of climate systems creates a special case where pattern extraction is greatly simplified.

Because the method as presented has no tuning parameters or climate system specific considerations,
the resulting patterns have the impartiality and repeatability that allow it to become a concensus result that can form the start or further research.










