:docinfo: shared
:imagesdir: ../fig/
:!webfonts:
:stylesheet: ../web/adoc.css
:table-caption!:
:reproducible:
:nofooter:

= Paper1
George Kontsevich

== Abstract

The interplay between recurring atmospheric processes and local topography creates regular observable climatic phenomena. We present a novel method for analyzing the spatial distribution of atmospheric parameters at the mesoscale which will allows for the extraction of a pair of underlying climate-associated shapes. The method builds on the singular value decomposition (SVD) and corrects for several difficiencies of a typical empirical orthogonal function (EOF) analysis. The extracted shapes act as unique fingerprints that allow one to observe climate without having to characterize it, without needing to understand any of its dynamics, and without building any heuristics. Key to making the EOF correction is the obersvation that many climate phenomena come in non-coocurring pairs. For instance the Summer/Winter Monsoons, El Nino / La Nina and the positive and negative phases of many climate systems. The presence of one climate state precludes the occurance of the other. As a result of this bistability, when reducing the measured climate parameters to two dimensions (by singular value decompositon) we will observe clustering around two linear combinations of the basis vectors. These two combinations can be found using a variance minimizing search (Otsu's method) and represent a simple mixture of the first two singular vectors (or EOF1 and EOF2). The mixtures' associated shapes can then be used to measure the presence of the climate phenomena in the original data to build a rolling two state climate index. We present several examples using the IMERG presciptiation dataset as well as with ERA5 precipitations model estimates. An  accompanying program for reproducing the analysis is provided.


TODO:
- How similar are the two shapes?
- What is the "variance of the mean" of the calculated centroid?
- How sensitive are the shapes to uniform noise?
- Angular distribution plot
- Plots are normalized to the highest value in-image (but that's not indicated anywhere)


== Introduction

Climate systems, such at the monsoons or El Nino/La Nina aquired their names when people native to a region note a recurring weather phenomena and ascribe it a name.
The typical modern approach is to characterize the causes and signatures associated with a particular recurring climate system.
However the original methodology, of pattern recognition comes naturally to the untrained eye. Arguably it still presents several distinct advantages. Chief among them are its generality and simplicity. Pattern recognition has been applied in the numerical field, particularly with the use of the singular value decomposition (SVD). As applied in the atmospheric sciences this has been known as the EOF (this is typically done an SVD on the anomaly). However results are often not meeting expectations.
Often the first EOF/singular-vector is used and subsequent ones are discarded. Why are there issues? Can they be addressed?

== Materials

- The first sections illustrate common issues with EOF analysis using synthetic data with know a-priori patterns. These are meant to provide a rough approximation of precipitation patterns as seen in the subsequent sections. Knowing the ground truth allows us evaluate results objectively.

- We then move on to using gridded precipitation data as provided by the IMERG Late dataset to help us demonstrate how our method yields a clear improvement in climate pattern extraction in real-world conditions. These are used at the monthly, daily and hourly levels.

- Lastly we move to using a coarser ERA5 reanalysis dataset as a point of comparison and to highlight the potential utility of having accurate climate patterns

Regions of interest will be:
- Southern Thailand and Peninsular Malaysia. A region affected by a summer monsoon system as well as a winter monsoon system.
- Maritime Continent - in particular southern Java

== Issues with the EOF

Typically EOF analysis suffers from several common issues. We make the following observations:

O1:: EOF patterns are orthogonal, climate patterns are generally not
O2:: All EOF patterns will represent a mixture of all underlying signals
O3:: EOF1 is biased towards the strongest signal
04:: Looking at changes in EOF1 and EOF2 creates a phase-lag artifact
O4:: At synoptic scales climate pattern shapes do not stay fixed. This creates incorrect patterns and makes energy "leak" in to secondary singular vectors.

All of these are illustrated using synthetic examples in the following section (Supplimentary)

== Synthetic illustrations of the EOF problem

The standard method for extracting signals from noise is based on the singular value decomposition (SVD). The method works in an iterative fashion, calculating the induced matrix norm of the dataset, removing it from the data and then repeating the process. For a single signal system this produces the best approximation of the underlying signal.

To observe the result we will work off of a known pattern.

image:imrg/pattern1.svg[]

We then perturbe this pattern to generate a test dataset. These will represent an idealized climate induced precipitation pattern over a region. To make the example more concrete we imagine it as 12 monthly precipitation accumulations. Each row representing a year of rain

.Probably need cleaner plot axis
image:imrg/synth1patt/all-cycle.svg[]

The SVD in effect performs a linear weighted sum of these input image such that we get a nice approximation of the underlying `t` shaped pattern.

image:imrg/synth1patt/sv-0.svg[]

The algorithm selects weights such that they maximizes the energy of the sum. The constraint (so that you can't pick arbitrarily large weights) is that the vector of your weights is of unit length. Such a sum effectively gives more weight to data that has higher values and data that has higher signal to noise ratios - as the data will effectively "stack up" producing a larger sum. The result should be superior to a straight average of all the data.

Note the blue color indicates negative values - a characteristic of most SVD numerical routines is that the first singular vector will be negative (negative weights). The result could be safely inverted. This would be equivalent to inverting the weight values. However, for simplicity I will keep the output vectors unaltered (as produced by the Intel MKL SVD routine).

We then expand the problem to a two pattern system. We have taken the previous data set and substituted the last four months with a secondary pattern.

image:imrg/pattern2.svg[]

This will act as a synthetic secondary winter climate pattern. We want to observe how a secondary signal affects our final analysis.

.Probably need cleaner plot axis
image:imrg/synth2patt/all-cycle.svg[]

Now when we perform the SVD, EOF1 (or the first singular vector) looks problematic.

image:imrg/synth2patt/sv-0.svg[]

The dominant signal from before is the most prominent feature, but the secondary pattern is also visible - illustrating issue O3. This should dispel the myth that EOF1 is somehow a safe basis b/c it is no affected by the orthogonality constraint. The orthogonality constraint naturally makes things even worse as EOF2 is even more difficult to visually interpret.

image:imrg/synth2patt/sv-1.svg[]

EOF2 has to be orthogonal to EOF1. The iterative nature of the SVD algorithm had first removed EOF1 from the dataset before computing EOF2. Hence all the remaining data was orthogonal to EOF1 and therefor their linear combination (EOF2) is also orthogonal. As a result EOF2 is even more strange and unrelated to the underlying signals. This is highlighting the reality of issue O2 - that all singular vectors are actually representing mixtures of all the signals and none can be directly interpreted as climate indicators (outside the simple and yet common case of only one climate system).

A detailed mathematical treatment of why all EOF vectors end up being mixtures is outside the scope of this paper. However, in short, this is a byproduct of how the weights (the singular values) are assigned. At face value, adding in a secondary signal seems to run counter to the goal of maximizing the energy of the sum. However the maximization is done by maintaining the 2-norm of the weights at 1.0. This can be restated as: the weights form a "unit vector" or the quadrature sum of the weights is equal to `1.0`. The quadrature sum means that counterintuitively, all else being equal, spreading weights out actually makes their direct sum a higher value. This can be illutrated by looking at a logical extremes. If all weight is assigned to one data point, then its weight will equal `1.0`. By contrast an even spread of weights across all data gives `N` weights of `1/sqrt(N)` and `N/sqrt(N) > 1.0` for all values of `N`. The end result is that secondary signals always get small weights assigned to them.

== Case Study: South East Asian monsoon systems

We work off of a real example so that the EOF problems can be visually confirmed. This will allow us to construct a simple correction that produces patterns with a much better fidelity to those we observe in the raw data.

Here we look at a Southern Thailand. The top of the Malay Pensinsula is climatologically challenging as it's subject to two distinct monsoon systems. The summer monsoon brings moisture from the Indian Ocean and drives precipitation for most of the year, while the winter monsoon system brings moisture from the East - the South China Sea and the Gulf of Thailand. There is also a short "dry season" at the beginning of the year that is modulated by the interannual ENSO system.

.Should be modified to the strip configuration??
image:imrg/krabi/monthly/year-stack.svg[]

Visually the two systems produce rainfall in two distinct patterns. The summer months have rain on the west coast, predominantly in the northern most sections. The late fall and early winter months show rain the south eastern section. The rain patterns represent a complex interplay between the local topography and the synoptic scale atmospheric configuration for large fractions of the year. In this case the areas of most rainfall correspond to coastal high mountains upwind in their associated monsoonal systems.

While the patterns are readily apparent in these monthly averages, we would like to extract the patterns in an objective manner (ie. without manual selection of "monsoon months" or any heuristics tuned to this climatological system). As a first attempt to observe the climate induces rain patterns, we perform a singular value decomposition on monthly rainfall. We choose a ten year period from 2011 to 2022 - for a total of 120 monthly snapshots.

image:imrg/krabi/monthly/sv-0.svg[]

The first singular vector gives us something that looks quite similar to the west coast precipitation associate with the summer monsoon. Signal mixing is not as apparent as in the synthetic example b/c the summer monsoon dominates annual rainfall. Furthermore, unlike in the synthetic example patterns in nature tend to be smoother - thereby masking the underlying mixing. However a careful eye will note that there is an intensification of precipitation on the East coast which does not occur in reality

image:imrg/krabi/monthly/sv-0.svg[]

The second signular vector, orthogonal to the first, look even harder to interpret but seems to correspond to a very strong east west contrast.

== Isolating correct patterns in the SV subspace

The root cause of the observed problems with the singular vectors (ie. EOFs) is that both vectors represent a mixture of both climate signals. First we observe that at a high level the local climate system can be approximation as a noise dominated system of two signals. Both singular vectors provide two different mixtures of these two signals. So by virtue of there being just two degrees of freedom, a certain mixture of the two singular vectors should represent a summer pattern - meanwhile a different mixture should correspond to a winter mixture

As a result we can reduce our problem space to two dimensions

image:imrg/krabi/monthly/sv-projs-plain.svg[]

In other words we can replot all 120 data points along two axes. The X axis show how closely a day corresponds to the first EOF, while the Y axis shows how closely the data point corresponds to the second EOF. These two projections correspond to the first two columns of the projection matrix in the SVD.

When observed in this subspace we make our second key observation: that the two climate systems are non-coocurring. Either atmospheric parameters are in some summer monsoon associated configuration or in a winter monsoon associated one. Since these processes happen at synoptic scales, much larger than the zone under observation, there is very little time spent "in-between". For instance the onset of the monsoon at the Southern end and Northern end of the selected region has been estimated to differ by approximately XXX days.

The two-state nature of the climate system means that in the 2D plane months form two clumps. Each monthy at a first approximation either look like one of two ratios of EOF1 to EOF2. To estimate these two ratios we use a procedure akin to Otsu's method in computer vision. We subdivide the 2D subspace along all possible diagonal dichotomies and find the dichotomy which minimizes the total variance. Such a dividing line in essence ensures both halves form a tight grouping around each half's mean

image:imrg/krabi/monthly/sv-projs.svg[]

Once the optimal divisor has been selected (red dashed line), we find the centroid of each half (black dotted line). This represents our estimate of each climate-associated ratio. The centroid is calculates as the average ratio of EOF1 to EOF2 across all points in each respective half (ie. an average of the angles of each point). Each point has an estimated two dimensional error and the resulting centroids have errors of their own (see: Supplimentary: Error Analysis). While many data points cluster near the origin, indicating a low climate signal, they do not corrupt the resulting estimates. The error estimates near the origin tend to result in large angular errors (ie. EOF1/EOF2 ratios) and thereby tend to contributing very little to the centroid/pattern estimates.

image:imrg/krabi/monthly/top-pattern.svg[]

We can then draw the ratio specified for each centroid. Here we first look at the top centroid. The monthy in the top half are blue/purple and correspond to the late-fall/winter months. The pattern represented by the ratio indeed corresponds to the pattern we observed in the raw data and matches our intuitive understanding of the climate configuration during the winter monsoon.

image:imrg/krabi/monthly/bottom-pattern.svg[]

Similarly the bottom half consists of summer months, and the centroid-associated ratio produces a mixture of EOF1 and EOF2 such that the resulting pattern looks like the summer monsoons we observed in the original data. Note how the previous artifacts we saw in EOF1, with spurous rains on the East coast, have completely vanished

== Error Analysis

There are generally two related sources of error in the previous method. One is the error in each points' projection on the 2D singular vector subspace. This is a two dimensional error of each point's decomposition into EOF1 and EOF2 components. The other is the error in the final patterns, ie. the calculated centroid of each half.

When we projected on to EOF1 and EOF2 we implicitely work under the simplifying assumption that there are only two climate systems. The remaining singular vectors (EOF3, EOF4 etc.) form what is effectively a background noise with an expected mean of zero. However a stochastic process with an expected mean of zero will have a non-zero measured mean at each data point. This is known as the variance of the mean, and it is equal to the variance divided by the number of points. The errors in the projections occur due to the noise in the EOF1 and EOF2 regions have such a nonzero mean.

Further complicating things, the background noise level is non-constant. Fortunately if the input data is high dimensional (ex: IMERG data is typically on the order of thousands of pixels get data point) the noise level can be estimated at each time point. Since the mean is already known (it is zero) we simply estimate the variance by looking at the variance of the data with EOF1 and EOF2 removed. However scaling the variance to get a variance of the mean is more complicated.

== Applications: Climate Patterns

The previous steps have given us clean non-orthogonal climate patterns. These can serve as a basis for further research. First, the spatial distribution of the pattern itself can serve as a source of truth. Second, once the pattern is isolated we can look for it in future (and past) data.

The pattern as a source of truth can be useful when for instance looking at changes in atmospheric paraters. However this needs to be evaluated on a case by case basis. A more direct approach would be for instance validating a climate model.


If we are to run the identical method on ERA5 monthly precipitation for the same period

We get the following winter monsoon associated pattern

And the following summer monsoon associated pattern


While the original data is at a coarser resolutions, the two patterns seem to generally correspond in this region.

== Applications: Climate Indeces

Using the pattern to look for the presence of climate at past and future times can form the bases of constructing climate indeces. Many climate indeces are built on the bases of using EOF analysis - particularly the first singular vector, EOF1. These methods typically give plausible results due to two common phenomena. First, as was noted before, most climate phenomena come in pairs. Second, often climate phenomena are close negatives of each other when viewed as anomalies from the mean. The rain patterns derived for the Thai peninsula, if normalized to be around zero, resemble negatives of each other. Similar near-negatives can be imagines for other climate phenomena, like the El Nino equatorial warm water tongue vs the La Nina subtropical heating, or the positive and negative phases of the southern annular mode, or the north atlantic dipole. This means that EOF1 (which is done on an anomaly and not raw data) for many regions may produce a pattern which gives a one dimension estimate of both climate phenomena. This however is not a property that is universaly true - and doesn't have a clear universal scientific rational

Using climate patterns provide by subspace bisection allows us to entirely avoid the serendipity of this second requirement. We treat each climate pattern separately and we will generate two independent indeces with non-comparable scalings. To build an index based on our climate data we simply need to project data on to our patterns. We use the bisecting line (red line Fig XX) to determine which pattern each data point should be projected on. The projection can either be done directly (ie. an innner product of the pattern and data) or can be done with a non orthogonal projection in the 2D singular vector subspace. We reject the nonorthogonal method because data points are conceptually attributed to one climate system or the other and don't represent a mixture.

image:imrg/krabi/monthly/indeces.svg[]

== Error Estimation



Climate patterns have been estimated, and then data reprojected and climate indeces calculate. But how confident can we be in the results? On the whole there are two sources of error. There is the error in the original pattern itself and there is an error in the estimates climate index. The first error is at the pixel level, while the second error is in the final calculated weight

The error in the pattern is the error in the estimated ratio calculated for both halves of the 2D subspace

== Stability under noise - extension to daily data

== Comparison to Climate model data

== Case Study: Diurnal cycles in the maritime continent

== Korean Peninsula

Large regions are dangerous
