:docinfo: shared
:imagesdir: ../fig/
:!webfonts:
:stylesheet: ../web/adoc.css
:table-caption!:
:reproducible:
:nofooter:

= Paper1
= Fixing the EOF by Climate Dipole Bifurcation
George Kontsevich

== Abstract

Large scale climate processes,
in their interplay with topography,
leave distinct fingerprints on the spatial distribution of regional weather.
If these spatial patterns were to be properly isolated,
an observer of the weather would be able to infer which climate system was active at any given time.
Building on the singular value decomposition (SVD),
we present a method for estimating these climate-associated patterns.
Mirroring the method of empirical orthogonal functions (EOF),
eshewing tuning parameters and heuristics ensures an impartial method that is region agnostic.
Key is recognizing that many dominant climate phenomena come in non-coocurring pairs.
When reduced to two dimensions by SVD,
weather records align around two linear combinations based on which climate dipole phase is active.
These combinations,
once isolated,
form the basis of regional two-state climate indices.
We present an example using the IMERG precipitation dataset,
along with software for reproducing the results.


WORD LIMIT: 150
WORDS: 149

== Introduction

Climate systems,
such at the monsoons or El Nino/La Nina,
acquired their names when people native to a region noted recurring weather phenomena.
By constract,
a typical modern approach for identifying climate system involves searching for and then characterizing repeated atmospheric configurations.
Nonetheless,
when climates are poorly understood or are still not well characterized,
the original methodology of pattern recognition comes naturally to the untrained eye.
While at times imperfect,
it presents a simple method that can be used regardless of location.
Pattern recognition,
as applied in the atmospheric sciences and oceanography,
has been typically done using empirical orthogonal function
(EOF)
analysis.
This is typically shorthand for a singular value decomposition
(SVD)
of some parameter's anomaly from a mean.
The resulting patterns,
(EOF1 EOF2 EOF3 etc.)
are meant to roughly represent the patterns that repeat in your observations.

Results are inconsistent and EOF patterns are often viewed with some skepticism;
primarily as a starting point for further quantitative analysis.

As will be explored,
the fundamental issues affecting EOFs are:

O1:: EOF patterns are orthogonal,
climate-associated patterns are generally not.
O2:: All EOF patterns,
including EOF1,
represent mixtures of all the underlying signals.
O3:: EOF1 will often be heavily biased towards the dominant climate signal,
giving the false impression it is correct/reliable.
O4:: When EOF patterns are attributed to climate phenomena,
the changes in EOF intensities over time create erroneous correlations.
One often finds a phase-lag-like relationships between EOF components;
the product of poor climate pattern isolation of the EOF patterns.

The fact that the EOF is built on the anomaly
(from some mean),
while a seemingly sensible starting point,
is in fact another source of hard-to-resolve issues.
At the heart of the issue is that,
in the presence of multiple climate systems,
mean structure does not typically correspond to a physically meaningful process.
Worse yet,
any such mean contains a mixture of all the climate patterns that were observed.
As a direct consequence,
when calculating anomalies from a constant mean,
one has in-effect taken every observations and subtracted some static mixture of every climate signals
that has occured
(and this mixing ratio is typically unknown).
Meanwhile,
looking at the actual climate associated patterns in the original observations,
they will have been some non-static value that is varying in intensity over time.
Operating on the anomalies means one now has to disentangle these constant patterns,
from the mean,
from the patterns in the original observations.
This needlessly complicates the pattern extractions process.

To sidestep this problem,
we confine ourselves to the using the SVD on original observations directly.
This means that instead of EOF1, EOF2, .. etc. we will use the singular vectors SV1 SV2 .. etc.

All the aforelisted issues (O1..4) hold just as well for the SVD as for the EOF.

Our objectives are:
first,
to conclusively illustrate the problems with the EOF1;
second,
to presenting a simple method for resolving them.

== Materials

- We first illustrate the aformentioned issues with EOF-like analyses using synthetic data.
While the synthetic weather model will be extremely basic,
it will to allow us to know a-priori which climate patterns are present.
When we try to extract patterns,
using the SVD,
we can observe discrepencies with the originals we have in hand.
Once we see the issues that occur,
we can identify the causes and start considering how we may resolve them.

- For a case study we look at precipitation over Peninsular Southern Thailand.
The region was chosen because of ongoing paleoclimatological work in the area. *REF*
The top of the Malay Peninsula is climatologically challenging.
It is subject to two distinct monsoon systems:
The dominant monsoon system is the so-called summer monsoon
(ie. boreal summer).
It brings moisture from the Indian Ocean and Andaman Sea.
The secondary system is the winter monsoon,
which primarily brings moisture from the East - the South China Sea and the Gulf of Thailand.

- To help us demonstrate an improvement over the EOF/SVD,
we test the method using gridded precipitation data.
For this we will use the "IMERG Late" dataset.
(**SUPP** Notes on IMERG)
In terms of pattern extraction,
we don't observe any sensitivity with regard to time bin size,
with daily to monthly bin sizes all produce near-identical climate patterns.
Nonetheless,
for the sake of visual clarity,
we present daily accumulations binned to pentads
(with leap days removed).
An equivalent analysis using daily data is provided in **SUPP**
IMERG has a 0.1x0.1 degree resolution.
This gives ample room to select small regions of interest.
As will be discussed,
operating on small regions directly benefits pattern extraction.

.Supplementary sections explore:
The Great Rift Valley:: A region with semi non seasonal climate signals.
Marrah Mountains (Sudan):: A region with one climate phenomena and the breakdown in one of the EOF assumptions.
Java Island:: Diurnal cycles with large errors and less stationary patterns
ERA5 reanalysis precipitation:: The method as used to validate climate model output
IMERG Final Result:: Showing artifacts caused by numerical normalization procedures


== Synthetic illustrations of the EOF/SVD problem

Using a synthetic dataset allows us to not only observe the aformentioned problems (O1..4),
but it will also give us insight in to a possible solution.
We start by creating two arbitrary patterns,
representing the two states of our climate system.
Since the pattern were chosen at random they will not be orthogonal to each other
(anticipating issue *O1*).
The patterns are then perturbed to create synthetic "observations".
For ease of interpretability,
the observations are arranged to mimick monthly precipitation accumulations of a monsoonal region.
First there are several summer-equivalent patterned observations.
This is followed by a shorter period of winter-equivalent patterned observations.

When we look at the first two singular vectors (SV) generated by the SVD,
the first thing that stands out are the negative values in the first singular vector (SV1).
These values,
colored in blue,
are characteristic of most SVD numerical routines. **REF** North?
Most such routines,
such as the Intel MKL library used here,
when run on purely positive observation such as rain,
will return negative values for the first singular vector.
In practical terms this does not turn out to be meaningful.
As a basis vector the sign could be safely inverted;
one would just need to invert all subsequent weight values.
Since it would be of no practical benefit,
we keep the singular vectors unaltered.

The next thing we notice are the mixed signals.
As we had stated in *O2*,
the SVD's singular vectors all end up looking like a mixtures of our original patterns.
For many climatologists it may come as a surprise that the first basis
(equivalent to EOF1)
has also been affected.
This mixing is a direct consequence of how the SVD is designed to extracts patterns.

.The SVD as an iterative algorithm
At a high level,
the SVD algorithm can be viewed as an iterative algorithm;
building singular vectors one after another.
Once a singular vector is created it is removed from the observations.
These new adjusted observations are then used to make the subsequent SV.
Note that "removing a singular vector" means removing any component in the same direction
(such that the inner product becomes zero).
As a result,
all the adjusted observations end up orthogonal to that SV.
When the next singular vector is built from these adjusted observations it too will be orthogonal.
This is because singular vectors are constructed by a linear combination of the observations
- so if all the adjusted observations are orthogonal,
then so will their combination.
This tells us that issue *O1* is a direct result of the algorithm's design.

.Singular Vector construction
To understand why the singular vectors
(even the first one)
end up mixing signal
(issue *O2*)
we need to understand what the SVD does at each iteration.
When building a singular vector,
for instance when building SV1,
the SVD is fundamentally doing a weighted average
(ie. linear combination)
of the data/observations.
The weighting is said to maximizes the induced matrix norm.
In other words,
the weights are selected such that the euclidean length
(2-norm)
of the resulting singular vector is as large as possible.
When looking at the singular vectors as pattern images
(as illustrated),
the euclidean length is effectively the sum of the squares of all the pixels.
The squaring causes the pattern extraction.
A straight sum
(the manhattan 1-norm)
would cause the algorithm to simply add observations with the most rain.
However,
the squaring drives the algorithm to favor sums that make some pixels have large values.
Large value have even larger squares and they drive up the euclidean length.
So if you want the square of the pixel-values to add up to a maximal value,
then at face value it seems one should add-up similar images
(ie. some repeating patterns)
so that pixels "added up" together;
even if the pattern is relatively small.

However,
what we actually see is that the singular vectors have multiple patterns at once.
This seems to run counter to the maximization objective.
The root cause is a subtlty of an algorithmic constraint we have elided.
When the SVD is maximizing this weighted average of the observations the weights must have been implicitely limited somehow
(so that the SVD can not pick arbitrarily large weights).
The limit is that the weights must be of unit length.
In other words,
the sum of the squares of all the weights must equal to `1.0`.
As previously,
the squaring makes a subtle but important difference
(here breaking the pattern extraction instead of enabling it).
As before,
while the sum of squares is a constant `1.0`,
the direct "normal" sum of weights is not constant.
All else being equal,
spreading weights out actually makes their sum a higher value.
This is most easily illustrated by looking at the logical extremes.
If all weight was assigned to just one observation
(for instance the one with the most total rain)
and all other weights were set to zero,
then the sum of weights would equal `1.0`
(same as the sum of squares).
By contrast,
an even spread of weights across all `N` observation would give each weight the size `1/sqrt(N)`
(here the sum of squares still equals `1.0` for all values of `N`).
This gives a direct sum of `N/sqrt(N)`.
Since `N/sqrt(N) > 1.0` for all values of `N`>`1`,
this tells us that the algorithm will have a tendency to spread weights.
As a result,
while observations that exhibit the dominant pattern do get higher weights
(to maximize the euclidean length),
the observations with secondary signals will also get small weights assigned to them
(to maximize the sum of the weights).

The end result is our SV1 vector ends up looking like a mixture of both underlying signals;
highlighting our issue *O2*.
Adjusting the ratio of the two climate pattern in the synthetic data,
we observe the mixing effect diminishes rapidly as the difference between climate signals increases;
which points us to issue *O3*.
However,
the mixing ratio is not something we have any analytic insight into,
hence we don't explore this thread further.

The next and perhaps even more glaring issue is the second Singular Vector (SV2).
As we just determined,
SV1 is some unknown mixture of the two patterns.
Before SV2 was constructed,
this mixture of patterns was removed from the observations.
As a result,
the adjusted observations
(which are no longer purely positive)
all had some component of both signals.
We can already speculate that a pure climate signal will not be extracted.
The maximization procedure still proceeds,
but because these adjusted observations were made orthogonal to the first mixture,
the possible outputs are constrainted.
What is interesting is that the maximization ends up returning a different mixture of the two original patterns;
with some negative and positive regions.

After the second singular vector is removed,
the remaining re-adjust observations have had all their patterns removed.
Hence all subsequent SV have no patterns present.
While we don't provide a rigorous proof,
the result comes naturally when viewing the degrees of freedom of the system.
The original two signals provided two degrees of freedom in our observations.
By removing the projections of two arbitrary signal-mixtures we must remove both signals from all the obervations.

The final result,
the first two SVs being different mixtures of the underlying signals,
ends up being the critical piece that will allow us to build a correction.

Because of the signal-mixing occuring in both singular vectors,
observing how SV1/SV2 (or EOF1/EOF2) change over time is a common source of false interpretations.
This is issue *O4*.
We leave a more detailed discussion for **SUPP**

== Case Study: South East Asian monsoon systems

We now repeat the same analysis on a real-world example in southern Thailand.
Here we do not have a priori knowledge of the climate associate patterns.
However,
we do have a some high level understanding of the climate configuration.
This should be sufficient to confirm the SVD/EOF problem.
Once confirmed,
we can construct a easily interpretable correction.
This will produce patterns with a much higher fidelity to those we observe in the raw data.

A preliminary visual inspection of the weather shows us that there are two distinct patterns.
The summer months have rain on the west coast,
predominantly in the northern-most part of the region.
The late fall and early winter months show rain in the south-eastern section.
These two rain patterns correspond to summer and winter monsoon systems.
At a high level,
the patterns are the result of a complex interplay between the local topography and the seasonal synoptic scale atmospheric conditions.
In this particular case,
the areas with the highest rainfall correspond to coastal mountains downwind of their corresponding monsoonal systems.

As in the synthetic example,
we first try to extract the underlying patterns by SVD.
The first singular vector gives us a shape that looks encouraging.
The shape at face value seems similar to the west coast precipitation associate with the summer monsoon.
Often an EOF anaylsis would stop at this point as the result doesn't have obvious glaring issues.
While our synethetic example showed that mixing must be happening due to issue *O2*,
it is not immediately apparent in this image due to a couple of reasons:

- First,
unlike in the more balanced synthetic example,
here summer monsoon rains form a dominant fraction of the annual total.
Issue *O3* strongly preserves the pattern.
- Second,
unlike our synthetic patterns,
natural patterns are typically smooth.
As a result,
their mixtures do not have large obvious artifacts.
Here only a careful eye will note the issue.
When looking at the first singular vector,
we see a small intensification of precipitation on the East coast which is not apparent in summer months.
The error in the pattern only becomes easy to detect once we have the corrected patterns for a side-by-side comparison.

The second singular vector,
orthogonal to the first,
shows some very strong east west contrast with both positive and negative values.
Not only does this not look like either climate system,
since we aren't working off an anomaly
(like in an EOF analysis)
the climate-associated patterns of precipitation should be positive.
Inverting the vector's values doesn't solve the issue;
as it would just creates other negative zones.

If we look at how SV1 and SV2 values change over time,
we will see a spurious relationship between the two.
Interpretting SV1 and SV2 as indicative of distinct climate phenomena may lead one to believe SV2 drives SV1.
If the signals are further normalized,
then this pattern can be misinterpreted as a phase-lag and create a false link between climate systems **REF**: MARTIME CONTINENT PAPER


== Isolating correct patterns in the SV subspace

We already know,
from our synthetic example,
that the root cause of the observed problems with the singular vectors stem from them representing mixtures of the underlying climate signals (*O2*).

Unless you are in a region with a single dominant climate system,
the singular vectors can not be safely used directly.
Unfortunately there is no simple way to differentiate single climate regions from mult-climate ones.
Such situations need to be identified by the researcher on a case-by-case basis.
For an indepth look at the common indicators of single system regions as well as associated challenges,
please see the Marrah Plateau example in **SUPP**

To isolate the climate systems we need to assume three simplifying characteristics:

A1:: the local climate system can be approximation as a noise dominated system of two signals.

A2:: these two climate systems by-in-large don't undergo any mixing.
In other words the two climates do not coocur.

A3:: The climate associated weather patterns scale in a near-linear fashion.
If it rains twice as much,
then it rains twice as much across the whole climate associated precipitation region.

These assumptions were in-fact implicit in the design of the synthetic example.

At face value *A1* seems like a onerous condition.
However,
in practice this seems to be a soft requirement.
For instance in the southern Thailand,
in addition to the monsoons,
we expect:

- at the seasonal scale we expect additional Madden Julian Oscillations (MJO) -
(see **SUPP**).
- at the interannual scale we expect some effects associated with the El Niño–Southern Oscillation (ENSO).

Yet when looking at the weather neither seem to cause visually apparent patterns.
Treated these other climate phenomena as background noise does not introduced notable issues in the final result.
More broadly,
the authors have not as of yet been able to find any locations with three or more visually distinct seasonal rain patterns.
Climate tripoles,
if they exist,
are likely extremely rare.

Characteristic *A2* will be at the root of fixing the SVD's climate signal mixing.
It's seldom observed that many climate systems are effectively forming dipoles.
This describes the winter and summer monsoons,
but also interannual systems like El Nino/La Nina.
There are many more such systems,
such as the Indian Ocean Dipole,
the afformentioned MJO,
the Southern Annular Mode,
the North Atlantic Oscillation as well as many others.
The key characteristics they all share is that both phases/systems do not coocur.

Assuming *A1* to be generally true,
and bulding on the intuition we developed in the synthetic case,
we can then interpret the first two singular vectors as each making an estimate of some unique mixtures of the two underlying signals.
By virtue of there being just two degrees of freedom,
a certain combination of the two SVs should give back one pattern,
while a different combination should give us back the other one.
In other words,
in our case study,
mixing SV1 and SV2 should give us back summer and winter monsoon patterns.

.Dimension reduction
To search for the mixtures we first simplify the problem.
We reduce our problem space to two dimensions.
This entails replot all our observations on to two axes;
SV1 and SV2 forming the X and Y axis respectively.
We could take the inner product of every observation with SV1 and SV2 and then plot.
In reality,
this projections are always calculate when building the singular vectors.
They will correspond to the first two columns of the SVD's left-singular-vector matrix.

The remaining discarded SVs
(SV3 SV4 ..)
can actually tell us a lot about the variability (or noise) in the weather.
This noise can then be used to estimate the errors in the SV1/SV2 projections.
While the error analysis is technically interesting,
it is tangential to the main thrust of the method.
We have left it to the supplementary section. **SUP**

Looking at our observations in this reduced 2D subspace,
we can immediately see the effect of the second simplifying assumption *A2*.
The climate dipole causes observations to form along two lines through the origin.
One grouping is dominated by summer (yellow) pentads while the other winter (blue/purple) pentads.
The two vectors,
along which the observations are aligning,
can also be seen as a representing a ratio of the singular vectors.
As we expect,
the vector containing the summer pentads lies close to SV1.
This corresponds to the dominant climate system.
SV1 was "summer-like" and hence the projections of summer pentads lie close to this axis.
By contrast the winter vector is off-axis.

We saw in the synthetic example that the SVs were mixtures of the climates.
Now we are seeing the inverse process;
the ratios of SV1 and SV2 that represent the alignment vector will serve to "unmix" the singular vectors and recover the patterns.

.Mixing ratio estimation
To find these vectors,
and their associated ratios,
we use a procedure akin to Otsu's method in computer vision.
We first subdivide the 2D subspace along all possible diagonal dichotomies.
In a 2D space the number of angular dichotomies increases linearly with the number of observations.
This allows the problem to remain solveable as the numbers of observations increases
(as compared to higher dimensions).
We then find which of these bisecting lines minimizes the total variance of both halves; ensuring that both halves form two tight groupings.
The specifics of the averaging and the error weighting is explained in greater detail in **SUPP**
Once the optimal bisector/dichotomy has been selected
(red dashed line),
we get out the two climate-associated ratios
(dashed line).

The fact that observations lie along these ratio vectors strong suggests that *A3* was a safe approximation.
Imagining a scenario with a breakdown in *A3*,
we would expect different climate-associated patterns between strong and weak monsoon periods
(the monsoon strength is indicated by the distance from the origin).
In such a scenario it would be very unlikely a static SV1 SV2 ratio could adequately describe both patterns.
The ratio would change in a consistent way based on the climate strength.
Looking at the SV1/SV2 plot of such a region,
one would expect the climate grouping to drift off-axis as observations were further from the origin.
Arguably in our case study the summer monsoon half does show a small off-axis trend.

With ratios in hand,
we can now draw them to see if they correspond to what we visually observed in the original data.
Both top and bottom ratios seem to closely correspond to the patterns we visually observed.
The winter months show rains on the South-East coast.
The summer months show rains on the North-West coast.
Note how the previous artifact we saw in SV1,
with spurious rains on the East coast,
has completely vanished.
Also notice how the positive offset is also gone.
We now get near-zero rain over downwind ocean sectors.

== Applications: Climate Patterns

The resulting patterns can serve as the basis for further research.

The pattern shape,
as described so far,
has been interpreted as a static consequence of recurrent large scale climate phenomena.
This simplified view may subtly break down in some scenarios.
For instance long term reconfigurations in the climate arrangement
(ex: wind direction)
could be investigated by comparing subtle changed in climate patterns over different periods.

Furthermore,
climate patterns,
even when static,
can serve as sources of truth for validating climate models and reanalysis datasets.
Running the method on the same region with the ERA5 dataset shows a close correspondence to the IMERG patterns. **SUPP**
Discrepencies,
if found,
could be a potential avenue for further investigation.

== Applications: Climate Indeces

Coming back to our original thesis.
Maybe more importantly,
these patterns allow us to objectively estimate the presence of climate in past and future observation.
Many modern climate indeces are built on the bases of the EOF
- particularly the first singular vector,
EOF1. **REF**
These indeces are also typically built over climate dipoles,
with the index having both positive and negative phases.
However,
it is only because of careful tuning that one EOF vector is able to discribe both phases.
Climate phenomena have a tendency to form near-mirror images when viewed as anomalies from the mean.
If one climate phase causes the wind blows East to West,
then most likely its negative phase blows West to East.
In our case study,
if rain patterns were normalized to a mean and you stenciled out the ocean,
the monsoons very roughly resemble negatives of each other - with an east/west north/south symmetry.

Similar near-negatives can be imagined for other climate phenomena.
For instance sea surface temperatures associated with ENSO;
the El Nino equatorial warm water tongue vs. the La Nina subtropical heating.
These two systems look like near negatives
- especially when viewed though carefully tuned boxes around the equator. **REF**
The positive and negative phases of the southern annular mode,
or the north atlantic dipole also look like negatives within their respective zones of influence.

As a consequence,
when working within a properly tuned region,
one may find EOF1
(which is done on an anomaly and not raw data)
produces a pattern which gives a workable estimate of both climate phenomena.
However,
this is not a property that is universally true
- nor does it have any clear universal physical basis.
Such EOF based indeces require validation by other heuristics.

Our climate dipole bisection avoids the serendipity of these extra symmetry requirements.
We not only don't need to characterize the climate or construct heuristics,
but we can also look at the presence of climate dipoles in less convenient regions.
This opens the door to potentially observe climate through many simultaneous regional patches;
allowing one to construct a synoptic scale understanding of climate systems.

To build an actual index we simply need to project data on to our patterns.
We use the bisecting line (red line Fig 2) to determine which climate system each observation belongs to.
The projection can either be done directly (ie. an inner product of the pattern and data) or can be done with a non orthogonal projection in the 2D singular vector subspace.
While in our dimension-reduced 2D view observations are shown as a mixtures of SVs,
neither the singular vectors,
nor the climate pattern themselves,
represent actual physical processes that are being mixed.
The variability in the plot is only attributable to noise before the dimension reduction.
Hence the final climate mixtures don't function as actual basis vectors.
Restated,
the intensity of a climate pattern in an observation is unrelated to the other climate phase's shape.
As a result,
the former direct inner product method is likely preferrable.

For the projection's error bound estimation see **SUPP**.

It's important to note that the two resulting climate indeces are not comparable.
Unlike a tuned EOF1 region which operates with one pattern,
here we have two separate patterns that are being projected on.
As a result,
it's important to remember that we can not make statements such as
"This year's summer monsoon was 20% stronger than the winter monsoon".
EOF1 bases climate indeces implicitely make such a comparison possible,
but the conclusions are likely erroneous and highly dependent on your tuned region.
When operating with two separate patterns such comparisons become explicitely not meaningful.

== Conclusions and limitations

Using a synthetic example,
We started by observing the serious issues with a typical EOF analysis.
Once we identified several likely causes,
we first simplified the mathematical formulation.
We skip the anomaly calculation and return to an SVD of unaltered observations.
We observe that the problematic singular vectors seem to preserve the climate patterns in a mixed state.
Then,
through a set of simplifying assumptions,
we formulated a simple physically interpretable method for extracting the patterns back out.

Points of failure worth discussion concentrate around breakdowns in our simplifying assumptions.
These generally fall in to several categories:

.A breakdown in assumption *A1*
This is caused by two scenarios:

The most common issue is that you have a single climate pattern that is forceably bisected.
Such scenarios typically have certain characteristic features.
Non-linearities in onset/withdrawl are exposed,
breaking assumption *A3*,
and you get characteristic on/off/on climate index patterns.
A characteristic example is explored in **SUPP**

The other possible issue is tertiary climate systems.
Such systems are typically of a different magnitude from the primary climate dipole.
While such systems should be evaluated on a case by case basis,
we have no identified any region where visibly interfers with the estimated climate-dipole patterns.
In our case study we manage to detect the effect of the MJO by using daily observations.
See **SUPP**
However,
this doesn't seem to have any observable impact on the resulting patterns.
A holistic framework for accounting for weaker tertiary signals will be an area of future work.

.A breakdown in assumption *A2*
Will causes certain characteristic issue in certain observations.
There are broadly three potential causes:
 1 :: the region under observation is too large.
For instance,
a region's southern section may be under a monsoonal regime, while the northern section has not yet been affected.
This causes energy "leaks" into lower power modes.
The effect should be apparent in the singular value scree plot.
 2 :: the observed parameter is slow to change.
For instance the period of wind reversal in a monsoonal region has an undefined shape.
 3 :: The integration time for each observation is too large.
If we perform this method on monthly precipitation averages we will often find months where both climate systems are active.

This third scenario will cause an observation that has a mixture of the two climate batters.
On the other hand,
The first two scenarios will have transition patterns of an indeterminable shape.

All the aforementioned issues are often readily observable in the SV1 SV2 plot.
These problematic observations will typically end up between the climate associate mixtures.
In our pentad case study,
arguably there are some observations that lie in the "in-between".
However,
in cases where the noise is very high,
looking at the 2D SV plot will be insufficient.
See: **SUPP**

All such observations end up skewing the estimates of the ratio axis.

We look at an extreme case using sea surface temperature in the South China Sea.
Here,
as the temperature transitions slowly,
we see the the second kind of issue.
**SUPP**

There is no universal turn-key way to account for these observations.
In most cases such observations constitute a small fraction of the total,
and therefore have a minimal impact on the result.
Issues can be minimized with a good estimate of the instananeous errors.
Transition states map poorly to the 2D subspace and these errors can be infered from the noise/error vectors
See: **SUPP**

Finally.
on a case by case basis one may build region specific heuristics.
If one has special insight in to climate transitions
(ex: there is some a priori knowledge that it only happens twice a year)
then one may try to find criteria for removing problematic observations from the SVD.
We have no found such heuristics necessary,
and caution they may mask other issues.

All these issues notwithstanding,
in a climate dipole region even skewed bisection patterns provide a clear improvement over the EOF basis.
The EOF basis is guaranteed to be an incorrect mixture,
and the second EOF's orthogonality constraint almost guarantees it will miss the mark.
Climate dipole bisection presents a clear,
physically motivated and mathematically simple correction.
This makes it much easier to interpret and accept than more complex EOF rotation routines.
SVD/EOF orthogonal rotation methods preserve the orthogonality issue.
SVD/EOF non-orthogonal rotation methods are difficult to physically interpret.
Independent Component Analysis present a compelling alternative that may give good results.
However,
it is a more general method that assume signal mixing and non-gaussian climate signals.
By contrast,
the presented method is mathematically much simpler

Finally,
because the method as presented has no tuning parameters or climate system specific considerations,
the resulting patterns have the impartiality and repeatability that allow it to become a concensus result that can form the start or further research.











====
Since these processes happen at synoptic scales,
much larger than the zone under observation,
there is very little time spent "in-between"
- and hence the space between the clusters only contains a few points
For instance the onset of the monsoon at the Southern end and Northern end of the selected region has been estimated to differ by approximately XXX days **REF**

This stresses the need to select small regions for climate pattern to properly cluster.
There may still be short transitionary periods at the regional/mesoscale,
but they constitute a small fraction of observations.
Furthermore,
the transition-associated pattern does not generally correspond to a mixture of the two climate systems.
This typically causes such states to have high estimated errors.
If one had a more sophisticated understanding of a particular climate dipole and its transition times,
this is a potentially area where one could construct a heuristic to squeeze more juice out of the method.
====

====
While some complex land-air interactions are occuring,
an observer does not need to understand them to visually identify the climates in question.
The patterns are evident without any understanding of the physical mechanisms behind them.
This suggests that we should be able to estimate climate-associated patterns without understanding them.
The motivation for this is severalfold.
For one,
such a method would present an objective,
climate-agnostic,
first step in observing climate systems.
We would entirely avoid needing to characterize the climate system in question;
obviating the need for heuristics or thresholding systems based on past statistics
**(Rainy Season of the Asian Pacific Summer Monsoon - Bin Wang)**.
Furthermore,
we should be able to leverage more data and get higher fidelity than typical conservative methods,
such as JJA or DJF means.
Aspirationally,
we may in theory be able to explore new climate processes that have not yet been identified/characterized.
====





== SUPP: Error Analysis

For the purpose of this analysis we will not be considering instrument error as this goes in to the specifics of the IMERG system and is outside the scope of the method

The error propagation will be explained in several steps:

1. We first will characterize the noise
2. Then we will explain how it affects the projections in the SV1 SV2 subspace of FIG????
3. This then will establish an error of the climate patterns themselves (FIG?? FIG??)
4. After which we can estimate the error of the climate index - ie. the projections of the time points on to the climate patterns themselves.

=== 1: The Noise

The simplifying characteristic A1 tells us that if we remove the first two singular vectors we are left with an estimate of the noise component of the system.

.De-noised data (ie. data with SV1 and SV2 removed)
image::imrg/krabi/monthly/noise-all.svg[]

The de-signaled data,
as expected,
looks like noise with no discernible climate patterns.
This remaining noise should have an expected value of zero.
Any non-zero value would in-effect indicate some additional climate signal,
which would run counter to *A1*.

The noise's variance generally increases with an increase in monsoon signal.
Visually we saw in FIG??? that the monsoon pattern manifests unevenly.
Intuitively,
we expect that when there is little signal/monsoon thing are dryer and the noise level is reduced.
When the climate signal is strong the noise level is higher.
At such times some patches may remain entirely dry,
while others may have large amounts of precipitation.

To observe this,
we can re-plot the months by their power in SV1+SV2 compared to the power of the remaining SVs (SV3,SV4,SV5,..etc).

.Signal to Noise plot
image::imrg/krabi/monthly/power-sv12-vs-other.svg[]

Unfortunately,
while there is a general linear relationship,
it isn't very robust.
There are many outliers and a lot of variability.

=== 2. Error in the 2D SV1 SV2 subspace

The noise level is important because it affects our estimates of projections.
While the expected value of the noise is zero,
the actual mean will never be exactly zero.
The variance of the measured mean is akin to the classic standard deviation of the mean (SDOM).
When you project your data on to a pattern (ex: SV1 or SV2),
the mean of the noise in areas of the pattern will be folded in to the projection.
So when calculating the inner product of the pattern and measurement,
the noise will cause you to either overestimate or underestimate the strength of your signal.

So when we took our data points and placed them on the SV1 SV2 plot (FIG????),
we had implicitly done this projection.
The noise's mean at every point in time was folded into the projections and had skewed our results.
While the size of the skew can't be know directly,
the magnitude can be estimated by knowing the variance of the noise.

For the purpose of this analysis we treat the SV1 and SV2 patterns/vectors as both having negligible errors relative to the data.

.TODO:
IS THIS A SAFE ASSUMPTION? DO I NEED TO ESTIMATE THE ERROR OF THE SV? CAN BE DONE BY DIVIDING DATASET AND CALCULATING.. OR SOME BOOTSTRAP?

We had originally gotten the projections by looking at the left singular vectors of the SVD.
However,
if done explicitly,
the projecting is done by taking the inner product of the data and the pattern.
Note that the left singular vectors are unit length,
While the projections are not.
So the final errors need to be divided by the corresponding singular value to be at the same scale
In other words we go pixel by pixel multiplying the pattern *P* with the data *D* and summing them all up:

stem:[sum_(pxl=1)^n P_{pxl}*D_{pxl}]

The pattern pixels *P* have negligible errors so we treat them as constant.
The data pixels for each time point *D* are some signal *S* with some noise *N*

stem:[sum_(pxl=1)^n P_{pxl}*(S_{pxl} +- N_{pxl)}]

We can separate this into the original inner product and the sum of zero mean errors:

stem:[sum_(pxl=1)^n P_{pxl}*S_{pxl} +  sum_(pxl=1)^n 0 +- P_{pxl}*N_{pxl}]

The best estimate of *S* is *D* so the left hand side is just our original inner product.
The error of the sum of errors is their quadrature sum.
So the final inner product will be:

stem:[sum_(pxl=1)^n P_{pxl}*S_{pxl} +- sqrt(sum_(pxl=1)^n (P_{pxl}*N_{pxl})^2)]

The last step is deciding on a value for *N*.
One option is to use the linear relation from FIG????.
However this presupposes a constant noise power across the whole field and that the noise level is purely a function of the signal strength.
Fortunately since the patterns fields are large and since we have many pixels and can directly estimate the noise level at every point in time.
If we treat each pixel as a separate random process with mean zero and unknown standard deviation then the designaled data gives us one trial.
The absolute value of the designaled pixel is our best estimate of of the standard deviation *N*.
So the error estimate is quadrature sum of the product of the designalled data and the pattern.

At this step the pattern *P* is either *SV1* or *SV2*.
The quadrature sum, after dividing by the corresponding singular value, provides the X and Y error in FIG????.
Note also that a larger pattern will make the relative noise smaller.

image::imrg/krabi/monthly/sv-projs-with-errors.svg[]

=== 3. Error in climate pattern

Now each data point in the SV1 SV2 plane has X and Y errors which we will call dX and dY.
To find the ratio of SV1 and SV2 associate with each climate pattern,
we first need to calculate the associated ratio for each data point.
If we calculate X/Y for each point then the associate error is the sum in quadrature of the fractional uncertainties:

stem:[X/Y +- sqrt(((dX)/X)^{2} + ((dY)/Y)^{2}]

.TODO:
- RATIO SEEM PROBLEMATIC AS IT EXPLODES TO HUGE VALUES AS Y GOES TO ZERO.
- MAYBE RADIANS?
- MAYBE PERCENTAGE OF SV1? (X/(X+Y))

When calculating the averages and variances of each half we now use these ratios with their associated errors.
Assume the errors are independent and normally distributed,
we can use the variances to make a weighted average and calculate a weighted variance

https://en.wikipedia.org/wiki/Inverse-variance_weighting

.TODO:
- SHOULD I ADDRESS THE INDEPENDENT/NORMAL CRITERIA..?
- OR FIND AN ELEGANT WAY TO ACKNOWLEDGE AND SKIP IT..?

When the variance minimizing divider is found,
the average will yield a ratio that corresponds to each the climate pattern.
The associated variance will specify the error in that ratio.
We can then use the error in the SV1 SV2 ratio to calculate average + error and average - error patterns and thereby calculate a pixel level standard deviation.
Naturally areas with high values in SV1 and SV2 will result in higher errors.

THE ERRORS "BARS" ARE LIKELY NOT SYMMETRIC.. NOT SURE HOW TO HANDLE/DISPLAY

.TODO:
- A MAP OR THE ERRORS FOR SUMMER AND WINTER MONSOONS??

=== 4. Error in Climate Index

The final error to be determined is the error in the final calculated climate index.
This is the projection of each time/data point on to each climate pattern.
Here the procedure is the same as when we projected on to SV1 and SV2.
However, while we treated SV1 and SV2 as having no effective error,
here we treat the climate patterns as having an error.

stem:[sum_(pxl=1)^n P_{pxl}*D_{pxl}]

So in the previous equation both P and D now have an error associated with them.

stem:[sum_(pxl=1)^n P_{pxl}*S_{pxl} +- N_{pxl}]

Here N is the quadrature sum of the fractional uncertainties.
We then proceed as before doing a quadrature sum of these combined probabilities.
This gives us the error bars on the final climate index projections.



== SUPP Pattern separation at different time scales

In our primary case study we look at precipitation totals at the pentad scale.
This integration time, or time box size, was chosen to help illustrate the method.
It gives nice separation in the SV12 subspace while avoiding the issue of longer time-boxes.

In this section we will do a quick overview of the behavior seen with larger and smaller integration times


=== Large time boxes

We first look at the issues that arise with larger time windows by looking at the same region using monthly precpitation values.
Monthly maps are provided directly by the IMERG

TODO: IMAGE OF MONTHLY SV12

What we start to see is a proportion of the higher energy (ie. further from the origin) data points lie between the two climate clusters. A large fraction of these occur during the late Fall (purple/violet) and correspond to transition points. The change from Summer Monsoon to Winter monsoon occurs rapidly in the region. The month-long time box in effect captures a certain amount of summer monsoon, indeterminate transition state, and winter monsoon. The final monthly map looks like a mixture of the two monsoon signals! This is an aliasing-type problem that runs counter to the method's built-in assumption that the climate will never coocurring.

== Small time boxes

We can also decrease the time box size. Decreasing the time step effectively provides us with more data points for a give period of time. The practical limit is a daily average - as any smaller time increment would need to contend with diurnal variability. Diurnal climate patterns are definitely present, but the separation of diurnal climate systems from seasonal (and potentially interannual) patterns is an area for future work and outside the scope of the current method. At the daily time-scale we may still observe transitional states, where neither climate system is established and hence neither pattern is present. However, we become less likely to capture actual mixing of mutliple climate systems in one integration time-step

When we observe the SV1 SV2 subspace again, we no longer see a distinct two-cluster system. At first glance it looks like all points are a mixture of the end members.

TODO: Image of daily SV12 subspace

However when we do our variance minimization method and look at the two centroids we find that the resulting patterns are identical

TODO: Daily patterns


Replotting all the data's angular component - a histogram shows that in the cloud of points you are getting two peaks. Each point is just perturbed by such a large amount of noise that the previously distinct clusters are lost. Unfortunately the variability in this subspace greatly exceeds the variability estimates in our Error Analysis, which suggests there is some room for improvement.

Looking at this spread one can't help but notice the wedge-like shape. These top and bottom edges of the wedge are not mixing end-member but in effect delimit an "allowed" zone of SV1 SV2 mixtures. Note how SV2 has large positive and negative values. Projections outside these zones would represent in mixtures that result in large negative zones in these SV1, SV2 component sums. Since precipitation must always be positive, the remaining noise would need to "fill in" these negative zones - which becomes increasingly unlikely as the zone becomes larger.

Looking at the resulting climate index we can oberserve the monsoons at the daily scale with with effectively a lot of noise. Some days in the middle of the summer are classified as winter monsoon days and vice versa. Since we don't have a good characterization of the variability we leave providing a comprehensive methodology for interpreting misclassified days as an area for future work. Re-interpreting the data in pentads or other time slices at the climate index level could potentially provide resolve this issue, but would require some criteria of a new integration window. If you know the there is one climate transition per year (ex: summer to winter monsoon) one could potentially tailor a statistical method to detect this transition point

In short, smaller time steps do not hurt the climate pattern extraction process, but may create an extremely high resolution noisy climate index that is challenging to interpret.

== SUPP Rift Valley: Non cyclical signals

Unlike many EOF enhancements, the methodology as currently illustrated does not make any assumptions about climate variability over time. There are no assumptions that one climate follows another or that they occur at similar times of the year/day. This allows us to look at some more unusual climate phenomena such as the rain patters of the Rift Valley in Eastern Africa

TODO: All (monthly?) data

Here there are two rain-associated climate systems which in Ethiopia as called the Belg and the Kiremt

https://agupubs.onlinelibrary.wiley.com/doi/full/10.1002/2016RG000544

TODO: Read this thing..

While boreal summer Kiremt rains come at a consistent time every year, Belg "short" rains as a lot less consistent and associated . However the illutrated method has no issue extracting these patterns.

TODO: SV12 projs

TODO: Patterns

TOOO: Climate index


== SUPP: Sahel Mountain (Marrah): Method used in a one signal region
Maybe the most common instance would be the one monsoon-related rainy season.
At the seasonal scale,
these climate systems are may be more the norm than the exception.
In these degenerate cases SV1 will be giving you a good approximation of the climate related pattern.
No extra steps are needed.
Unfortunately,
at the moment there is no clear statistical method identifying which regions have climate dipoles.
An ad hoc method is looking at the singular values in a scree plot.
However,
there is no clear line between a two climate system and one where characteristic *A3* have broken down.
Non linearities in climate associated patterns may cause Onset/withdrawal periods to present patterns distinct from the main climate associated period.
For an example of this phenomena see the Marrah Plateau in **SUPP**
Such situations need to be identified by the researcher on a case-by-case basis.


It must be noted that globally, most locations do not feature a bistable climate. The most common scenario is a simple one-system precipitation climate (at the seasonal scale). In these locations no tricks are necessary. The first singular vector (or first EOF) will extract the single pattern.

So it is interesting to try to observe what occurs if we apply your method in these situations. As a case study we look at the Marrah mountains in southern Sudan. This massif lies at the edge of the Sahel and is subject to a single monsoon-driven rainy season. The massif's topography has some interplay with the monsoon related atmospheric configuration which drives the dominant precipitation pattern.

TODO: SV12 plot

First note that we no longer see a clear separation in the SV12 subspace. The data presents an even spread across the allowable wedge. The two extracted patterns no longer have a clear physical interpretations

TODO: Pattern 1 &2

But when we look at the resulting climate pattern we do see a consistent pattern

TODO: Climate index

The single pattern is being torn apart in to a monsoon signal and an onset/withdrawl pattern. Remember that one of the assumptions of the EOF  (A3) was that:
" The climate patterns in question scale in a near-linear fashion.
If it rains twice as much,
then it rains twice as much across the whole climate associated precipitation region"

Here we see this assumption fall apart as the weaker onset/withdrawl monsoon takes on a warped shaped as compared to the middle of the rainy season.
This onset/withdrawl false pattern occurs regularly when the method is applied in single-system regions and is a good indicator that the method should skipped in favor of simply using the first singular vector (or first EOF1).

A look at the singular values confirms also gives us a strong indication there is effectively no second climate system at the seasonal scale

== SUPP Diurnal cycles: Maritime continent
So far we have limited ourselves to seasonal climate systems. However the method may work at other time scales. Here we present a quick examination of the diurnal cycle off the coast of Java for the period (TODO Specify period):

TODO: Data image

Again IMERG can be used as it provides extremely high resolution data at the half hour interval

TODO: SV12 plot

We again get some separation ..

A lot of intermediary state

Very noisy input

But it kinda works..
And you can have a lot more input data

Watch out for seasonal signals.
Separation of signals at different time scales is outside the scope of the paper



== SUPP Korean Peninsula: Large Region vs Small Region

We noted in passing that working at the mesoscale allows us to get clear climate onset/withdrawl.
Here we present results when a region that is too large is used.
We look at the Korean Peninsular at two different scales

Things go bad


== SUPP: Notes on IMERG

For the Southern Thailand case study we selected to use the V06B Late data provided by IMERG (in GeoTIFF format). We find that other versions produce notable issues related to a "climatological adjustment" made using GPCC gauge data. This rain gauge correction was added to the "Final" version of version V06B. In version V07B the correction is incorporated in both Late and Final version. The Early version is still unaffected, however it "only has forward propagation (which basically amounts to extrapolation forward in time), while the Late has both forward and backward propagation (allowing interpolation)". See: https://gpm.nasa.gov/data/imerg FAQ Section.

The adjustment creates a notable stenciling effect. The stencil seems to reflect the GPCC stencil seen in GPCC precipitation maps:
https://climatedataguide.ucar.edu/climate-data/gpcc-global-precipitation-climatology-centre

Here is an example using v7 monthly data:

TODO add images

V06 is provided in several different subversion. One is labeled V06B and GeoTIFF files are provided through 2022-05-07. The next next period goes through multiple version through 2024-06-02. To avoid any discontinuities in the analysis. We look at v06B data exclusively on the 2011-01-01 to 2020-12-31 (inclusive) period.

To simplify the analysis and create even annual cycles we subdivide the 365 day calandar year into pentads by removing all occurances of the leap day - February 29th.



== Long Abstract

=== V1

The interplay between recurring atmospheric processes and local topography creates regular observable climatic phenomena.
We present a novel method for analyzing the spatial distribution of atmospheric parameters at the mesoscale,
which will allows for the extraction of a pair of underlying climate-associated shapes.
The method builds on the singular value decomposition (SVD) and corrects for several deficiencies of a typical empirical orthogonal function (EOF) analysis.
The extracted shapes act as unique fingerprints that allow one to observe climate without having to characterize it,
without needing to understand any of its dynamics,
and without building any heuristics or adjusting tuning parameters.
Key to making the EOF correction is recognizing that a large fraction of climate phenomena come in non-coocurring pairs.
Systems such as the Summer/Winter Monsoons,
El Nino / La Nina and the positive and negative phases of many climate systems are all typically in one of two modes.
In effect the presence of one climate state precludes the occurrence of the other.
As a result of this bistability,
when using the SVD to reduce the measured climate parameters to two dimensions we observe clustering around two linear combinations of the basis vectors.
These two combinations can be found using a variance minimizing search (Otsu's method) that terminates at an optimal solution and represent a simple mixture of the first two singular vectors.
The mixtures' associated shapes can then be used to measure the presence of the climate phenomena in the original data to build a rolling two state climate index.
We present several examples using the IMERG precipitation dataset,
the ERA5 precipitations model estimates and a small synthetic data example.
An accompanying program for reproducing the analysis is provided.


=== V2

Many climate phenomena historically aquire names by a process of pattern-matching by local observers.
In simple terms,
large scale climate conditions are observed to cause a higher likelyhood of some corresponding weather.
While the naming of phenomena is useful,
due to the inherant variability,
local weather observation are never sufficient for inferring the current climate state.
However,
by observing weather across a region,
(ie. many locales simultaneously)
we can start to make stronger inferrence about the prevailing large scale climate conditions.
The climate's statistically significant effect on the weather is complex and region specific.
Without characterizing any of the dynamics,
we can safely assume it will almost certainly be spatially irregular.
This will be due to some complex interplay between atmospheric parameters and the local topography.
Here we present a novel method for analyzing the spatial distribution of weather at the mesoscale.
By looking at weather over a given region we can extract each climate's associate associate patterns.
Then using the extracted spatial patterns we can reanalyze our weather's conformance to the pattern.
Thus allowing us to infer the prevailing climate conditions for a given point in time.
The method builds on the singular value decomposition (SVD).
We remove the need for working off of an anomaly -
as is seen in a typical empirical orthogonal function (EOF) analysis.
More importantly,
we find a way to resolve the EOFs orthogonality constraint.
Key to the new approach is recognizing that many climate phenomena come in non-coocurring pairs.
Systems such as the Summer/Winter Monsoons,
El Nino / La Nina as well as the positive and negative phases of many other climate dipoles.
The critical characteristic of a climate dipole is that the presence of one climate state precludes the occurrence of the other.
As a result of this bistability,
when the the measured climate parameters are reduced to two dimensions by SVD,
we observe clustering around two linear combinations of the basis vectors.
These two combinations can be isolated using a variance minimizing search (Otsu's method) that terminates at an optimal solution and represent a simple mixture of the first two singular vectors.
The mixtures can then be used to form the basis of a two state climate index.
We present several examples using the IMERG precipitation dataset,
the ERA5 precipitations model estimates and a small synthetic data example.
An accompanying program for reproducing the analysis is provided.


