:docinfo: shared
:imagesdir: ../fig/
:!webfonts:
:stylesheet: ../web/adoc.css
:table-caption!:
:reproducible:
:nofooter:




=== Applications: Climate Indices

Coming back to our original thesis.
Maybe more importantly,
these patterns allow us to objectively estimate the presence of climate in past and future observation.
Many modern climate indices are built on the EOF
- particularly using the first singular vector,
EOF1. **REF**
These indices are also typically built over climate dipoles,
with the index having both positive and negative phases.
However,
it is only because of careful tuning that one EOF vector is able to describe both phases.
Climate phenomena,
when viewed as anomalies from a mean,
have a tendency to form near-mirror images.
If one climate phase causes the wind to blow East to West,
then most likely its negative phase blows West to East.
In our case study,
if rain patterns were normalized to a mean and you stenciled out the ocean,
the monsoons would very roughly resemble negatives of each other -
with an east/west north/south symmetry.

Similar near-negatives can be imagined for other climate phenomena.
For instance sea surface temperatures associated with ENSO;
the El Nino equatorial warm water tongue vs. the La Nina subtropical heating.
These two systems look like near negatives
- especially when viewed though carefully tuned boxes around the equator. **REF**
The positive and negative phases of the north Atlantic dipole also look like negatives within a szones of influence.

As a consequence,
when working within a properly tuned region,
one may find EOF1
(which is done on an anomaly and not raw data)
produces a pattern which gives a workable estimate of both climate phenomena.
However,
this is not a property that is universally true
- nor does it have any clear universal physical basis.
Such EOF based indices require validation by other heuristics.

Our climate dipole bisection avoids the serendipity of these extra symmetry requirements.
We not only don't need to characterize the climate or construct heuristics,
but we can also look at the presence of climate dipoles in less convenient regions.
This opens the door to potentially observe climate through regional patches;
allowing one to construct a synoptic scale understanding of climate systems.

To build an actual index we simply need to project observations on to our patterns.
We use the bisecting line (red line Fig 2) to determine which climate system each observation belongs to.
The projection can either be done directly (ie. an inner product of the pattern and data) or can be done with a non orthogonal projection in the 2D singular vector subspace.
While in our dimension-reduced 2D view observations are displayed as a mixtures of SVs,
neither the singular vectors,
nor the climate pattern themselves,
represent actual physical processes that are being mixed.
The variability in the plot is only attributable to noise before the dimension reduction.
Hence the final climate mixtures don't function as actual basis vectors.
Restated,
the intensity of a climate pattern in an observation is unrelated to the other climate phase's shape.
As a result,
the former direct inner product method is likely preferable.

For the projection's error bound estimation see **SUPP**.

It's important to note that the two resulting climate indices are not comparable.
Unlike a tuned EOF1 region which operates with one pattern,
here we have two separate patterns that are being projected on.
As a result,
it's important to remember that we can not make statements such as
"This year's summer monsoon was 20% stronger than the winter monsoon".
EOF1 based climate indices implicitly make such a comparison possible,
but the conclusions are likely erroneous and highly dependent on the selected region.
With two separate patterns such erroneous comparisons become explicitly not possible.

To see a daily climate index,
see *SUPP*.


== *A3* Breakdown

The fact that observations lie along these ratio vectors strongly suggests that *A3* was a safe approximation.
Imagining a scenario with a breakdown in *A3*,
we would expect different climate-associated patterns between strong and weak monsoon periods
(the monsoon strength is indicated by the distance from the origin).
In such a scenario it would be very unlikely a static SV1 SV2 ratio could adequately describe both patterns.
The ratio would change in a consistent way based on the climate strength.
Looking at the SV1/SV2 plot of such a region,
one would expect the climate grouping to drift off-axis as observations were further from the origin.
Arguably in our case study the summer monsoon half does show a small off-axis trend.







== SUPP: Error Analysis

For the purpose of this analysis we will not be considering instrument error as this goes in to the specifics of the IMERG system and is outside the scope of the method

The error propagation will be explained in several steps:

1. We first will characterize the noise
2. Then we will explain how it affects the projections in the SV1 SV2 subspace of FIG????
3. This then will establish an error of the climate patterns themselves (FIG?? FIG??)
4. After which we can estimate the error of the climate index - ie. the projections of the time points on to the climate patterns themselves.

=== 1: The Noise

The simplifying characteristic A1 tells us that if we remove the first two singular vectors we are left with an estimate of the noise component of the system.

.De-noised data (ie. data with SV1 and SV2 removed)
image::imrg/krabi/monthly/noise-all.svg[]

The de-signaled data,
as expected,
looks like noise with no discernible climate patterns.
This remaining noise should have an expected value of zero.
Any non-zero value would in-effect indicate some additional climate signal,
which would run counter to *A1*.

The noise's variance generally increases with an increase in monsoon signal.
Visually we saw in FIG??? that the monsoon pattern manifests unevenly.
Intuitively,
we expect that when there is little signal/monsoon thing are dryer and the noise level is reduced.
When the climate signal is strong the noise level is higher.
At such times some patches may remain entirely dry,
while others may have large amounts of precipitation.

To observe this,
we can re-plot the months by their power in SV1+SV2 compared to the power of the remaining SVs (SV3,SV4,SV5,..etc).

.Signal to Noise plot
image::imrg/krabi/monthly/power-sv12-vs-other.svg[]

Unfortunately,
while there is a general linear relationship,
it isn't very robust.
There are many outliers and a lot of variability.

=== 2. Error in the 2D SV1 SV2 subspace

The noise level is important because it affects our estimates of projections.
While the expected value of the noise is zero,
the actual mean will never be exactly zero.
The variance of the measured mean is akin to the classic standard deviation of the mean (SDOM).
When you project your data on to a pattern (ex: SV1 or SV2),
the mean of the noise in areas of the pattern will be folded in to the projection.
So when calculating the inner product of the pattern and measurement,
the noise will cause you to either overestimate or underestimate the strength of your signal.

So when we took our data points and placed them on the SV1 SV2 plot (FIG????),
we had implicitly done this projection.
The noise's mean at every point in time was folded into the projections and had skewed our results.
While the size of the skew can't be know directly,
the magnitude can be estimated by knowing the variance of the noise.

For the purpose of this analysis we treat the SV1 and SV2 patterns/vectors as both having negligible errors relative to the data.

.TODO:
IS THIS A SAFE ASSUMPTION? DO I NEED TO ESTIMATE THE ERROR OF THE SV? CAN BE DONE BY DIVIDING DATASET AND CALCULATING.. OR SOME BOOTSTRAP?

We had originally gotten the projections by looking at the left singular vectors of the SVD.
However,
if done explicitly,
the projecting is done by taking the inner product of the data and the pattern.
Note that the left singular vectors are unit length,
While the projections are not.
So the final errors need to be divided by the corresponding singular value to be at the same scale
In other words we go pixel by pixel multiplying the pattern *P* with the data *D* and summing them all up:

stem:[sum_(pxl=1)^n P_{pxl}*D_{pxl}]

The pattern pixels *P* have negligible errors so we treat them as constant.
The data pixels for each time point *D* are some signal *S* with some noise *N*

stem:[sum_(pxl=1)^n P_{pxl}*(S_{pxl} +- N_{pxl)}]

We can separate this into the original inner product and the sum of zero mean errors:

stem:[sum_(pxl=1)^n P_{pxl}*S_{pxl} +  sum_(pxl=1)^n 0 +- P_{pxl}*N_{pxl}]

The best estimate of *S* is *D* so the left hand side is just our original inner product.
The error of the sum of errors is their quadrature sum.
So the final inner product will be:

stem:[sum_(pxl=1)^n P_{pxl}*S_{pxl} +- sqrt(sum_(pxl=1)^n (P_{pxl}*N_{pxl})^2)]

The last step is deciding on a value for *N*.
One option is to use the linear relation from FIG????.
However this presupposes a constant noise power across the whole field and that the noise level is purely a function of the signal strength.
Fortunately since the patterns fields are large and since we have many pixels and can directly estimate the noise level at every point in time.
If we treat each pixel as a separate random process with mean zero and unknown standard deviation then the designaled data gives us one trial.
The absolute value of the designaled pixel is our best estimate of of the standard deviation *N*.
So the error estimate is quadrature sum of the product of the designalled data and the pattern.

At this step the pattern *P* is either *SV1* or *SV2*.
The quadrature sum, after dividing by the corresponding singular value, provides the X and Y error in FIG????.
Note also that a larger pattern will make the relative noise smaller.

image::imrg/krabi/monthly/sv-projs-with-errors.svg[]

=== 3. Error in climate pattern

Now each data point in the SV1 SV2 plane has X and Y errors which we will call dX and dY.
To find the ratio of SV1 and SV2 associate with each climate pattern,
we first need to calculate the associated ratio for each data point.
If we calculate X/Y for each point then the associate error is the sum in quadrature of the fractional uncertainties:

stem:[X/Y +- sqrt(((dX)/X)^{2} + ((dY)/Y)^{2}]

.TODO:
- RATIO SEEM PROBLEMATIC AS IT EXPLODES TO HUGE VALUES AS Y GOES TO ZERO.
- MAYBE RADIANS?
- MAYBE PERCENTAGE OF SV1? (X/(X+Y))

When calculating the averages and variances of each half we now use these ratios with their associated errors.
Assume the errors are independent and normally distributed,
we can use the variances to make a weighted average and calculate a weighted variance

https://en.wikipedia.org/wiki/Inverse-variance_weighting

.TODO:
- SHOULD I ADDRESS THE INDEPENDENT/NORMAL CRITERIA..?
- OR FIND AN ELEGANT WAY TO ACKNOWLEDGE AND SKIP IT..?

When the variance minimizing divider is found,
the average will yield a ratio that corresponds to each the climate pattern.
The associated variance will specify the error in that ratio.
We can then use the error in the SV1 SV2 ratio to calculate average + error and average - error patterns and thereby calculate a pixel level standard deviation.
Naturally areas with high values in SV1 and SV2 will result in higher errors.

THE ERRORS "BARS" ARE LIKELY NOT SYMMETRIC.. NOT SURE HOW TO HANDLE/DISPLAY

.TODO:
- A MAP OR THE ERRORS FOR SUMMER AND WINTER MONSOONS??

=== 4. Error in Climate Index

The final error to be determined is the error in the final calculated climate index.
This is the projection of each time/data point on to each climate pattern.
Here the procedure is the same as when we projected on to SV1 and SV2.
However, while we treated SV1 and SV2 as having no effective error,
here we treat the climate patterns as having an error.

stem:[sum_(pxl=1)^n P_{pxl}*D_{pxl}]

So in the previous equation both P and D now have an error associated with them.

stem:[sum_(pxl=1)^n P_{pxl}*S_{pxl} +- N_{pxl}]

Here N is the quadrature sum of the fractional uncertainties.
We then proceed as before doing a quadrature sum of these combined probabilities.
This gives us the error bars on the final climate index projections.



== SUPP Pattern separation at different time scales

In our primary case study we look at precipitation totals at the pentad scale.
This integration time, or time box size, was chosen to help illustrate the method.
It gives nice separation in the SV12 subspace while avoiding the issue of longer time-boxes.

In this section we will do a quick overview of the behavior seen with larger and smaller integration times


=== Large time boxes

We first look at the issues that arise with larger time windows by looking at the same region using monthly precpitation values.
Monthly maps are provided directly by the IMERG

TODO: IMAGE OF MONTHLY SV12

What we start to see is a proportion of the higher energy (ie. further from the origin) data points lie between the two climate clusters. A large fraction of these occur during the late Fall (purple/violet) and correspond to transition points. The change from Summer Monsoon to Winter monsoon occurs rapidly in the region. The month-long time box in effect captures a certain amount of summer monsoon, indeterminate transition state, and winter monsoon. The final monthly map looks like a mixture of the two monsoon signals! This is an aliasing-type problem that runs counter to the method's built-in assumption that the climate will never coocurring.

== Small time boxes

We can also decrease the time box size. Decreasing the time step effectively provides us with more data points for a give period of time. The practical limit is a daily average - as any smaller time increment would need to contend with diurnal variability. Diurnal climate patterns are definitely present, but the separation of diurnal climate systems from seasonal (and potentially interannual) patterns is an area for future work and outside the scope of the current method. At the daily time-scale we may still observe transitional states, where neither climate system is established and hence neither pattern is present. However, we become less likely to capture actual mixing of mutliple climate systems in one integration time-step

When we observe the SV1 SV2 subspace again, we no longer see a distinct two-cluster system. At first glance it looks like all points are a mixture of the end members.

TODO: Image of daily SV12 subspace

However when we do our variance minimization method and look at the two centroids we find that the resulting patterns are identical

TODO: Daily patterns


Replotting all the data's angular component - a histogram shows that in the cloud of points you are getting two peaks. Each point is just perturbed by such a large amount of noise that the previously distinct clusters are lost. Unfortunately the variability in this subspace greatly exceeds the variability estimates in our Error Analysis, which suggests there is some room for improvement.

Looking at this spread one can't help but notice the wedge-like shape. These top and bottom edges of the wedge are not mixing end-member but in effect delimit an "allowed" zone of SV1 SV2 mixtures. Note how SV2 has large positive and negative values. Projections outside these zones would represent in mixtures that result in large negative zones in these SV1, SV2 component sums. Since precipitation must always be positive, the remaining noise would need to "fill in" these negative zones - which becomes increasingly unlikely as the zone becomes larger.

Looking at the resulting climate index we can oberserve the monsoons at the daily scale with with effectively a lot of noise. Some days in the middle of the summer are classified as winter monsoon days and vice versa. Since we don't have a good characterization of the variability we leave providing a comprehensive methodology for interpreting misclassified days as an area for future work. Re-interpreting the data in pentads or other time slices at the climate index level could potentially provide resolve this issue, but would require some criteria of a new integration window. If you know the there is one climate transition per year (ex: summer to winter monsoon) one could potentially tailor a statistical method to detect this transition point

In short, smaller time steps do not hurt the climate pattern extraction process, but may create an extremely high resolution noisy climate index that is challenging to interpret.



== SUPP Diurnal cycles: Maritime continent
So far we have limited ourselves to seasonal climate systems. However the method may work at other time scales. Here we present a quick examination of the diurnal cycle off the coast of Java for the period (TODO Specify period):

TODO: Data image

Again IMERG can be used as it provides extremely high resolution data at the half hour interval

TODO: SV12 plot

We again get some separation ..

A lot of intermediary state

Very noisy input

But it kinda works..
And you can have a lot more input data

Watch out for seasonal signals.
Separation of signals at different time scales is outside the scope of the paper



== SUPP Korean Peninsula: Large Region vs Small Region

We noted in passing that working at the mesoscale allows us to get clear climate onset/withdrawl.
Here we present results when a region that is too large is used.
We look at the Korean Peninsular at two different scales

Things go bad


