:imagesdir: ../fig/
:!webfonts:
:stylesheet: ../web/adoc.css
:table-caption!:
:reproducible:
:nofooter:

= SUPP: CDB as EOF Rotation and Projections

At a high level the following discussion is in large part semantic.
However,
it will have some real implications for how we project observations on a climate patterns

== FIG Climate Dipole Bisection Example
image:imrg/errors/new-sv-projs-full.svg[]


=== Rotated EOFs

It's naturally to see Climate Dipole Bisection as another EOF rotation method.
While this formulation is not entirely incorrect,
it is a bit of a dangerous way to think of the final result.
As we will illustrate,
observations in such a rotated basis do no convey any information.

The first issue is maybe more conceptual:
We have not really rotated EOF1 and EOF2 to a particular positions.
You can think of EOF1 as being moved to the top quadrant and EOF2 to the bottom quadrant,
but this is neither a two step process,
nor is one quadrant more important than the other.

The larger issue is that,
while we are finding estimate of patterns in this subspace,
physically these patterns represent non-mixing elements.

SV1 and SV2 represent some estimates of particular mixtures of the underlying patterns.
Noisy observations map to yet mixtures of these SV1 and SV2 vectors.
In other words,
we have mixtures of mixtures.
From these we are making an estimate of the original patterns.

The conceptual leap is that,
once you have estimated patterns,
it is not meaningful to re-express observations as mixtures of climate patterns.
We could remap the observations to an nonorthogonal 2D space,
with the two patterns as the basis vectors,
but this would not be a useful basis.
In fact it would be actively depicting something non-physical.
We know that based on assumption *A2* the underlying patterns can not mix.
Ex: summer and winter monsoons have no physical way to manifest at the same time
(exception in the edge case of integration times that are too long).
Furthermore,
looking in such a nonorthogonal subspace,
some observations go so far as to imply the presence of negative climate pattern!

Since the rotated basis does not make physical sense, what are we left to do?

=== Projections
The solution ties in to the problem of projection.
This is the step that transforms our observations to a climate index.

==== Nonorthogonal

Normally,
when one has an nonorthogonal basis,
one should do a nonorthogonal projections.
Graphically,
they can either be done in the original SV1 SV2 subspace,
or one could build a 2D plot with the patterns as the basis vectors.
But as we just discussed,
this just doesn't make a lot of physical sense and we think this is an incorrect formulation.
Nonorthogonal projecting would indirectly imply there is a "dipole basis" -
but assumption *A2* implies nothing can lie off-axis in such a basis.

==== Orthogonal

The solution is to use the SV1 SV2,
ie. this original reduce EOF basis,
purely for pattern estimation and classification.
In other words,
the SV1 SV2 subspace helps you estimated the SV1 SV2 mixtures that reconstruct the climate patterns.
It also gives you the dichotomy (red dashed line) which classifies your observations in to two dipole states.

Once we have the estimated patterns and the classification we can discard this subspace entirely.
To calculate the correspondence of an observation to a pattern we simply do a normal projection/inner-product.

Since the SV3,4,5 subspaces should be mean-zero noise components,
such a projection should be equivalent to doing an orthogonal
(shortest distance)
projection in the SV1 SV2 subspace.
Measurements at this point lie along one pattern axis or the other,
and any off-axis shifts are simply due to noise.

So what we do not want to do is redraw the observations in a 2D subspace with climate A on the X axis and climate B on the Y axis.

In effect what we do not want is a Rotated SV basis.


