= Paper1

The interplay between recurring atmospheric processes and local topography creates regular observable climatic phenomena. We present a novel way for analysizing the spatial distribution of atmospheric parameters which extracts their underlying climate-associated shapes. These shapes act as unique fingerprints that allow us to observe climate without having to characterize it. The method builds on the widely used EOF method, but leverages two key insights to refine the result. First, at the mesoscale, climate patterns tend to be stationary with clear shapes and few transition states. Secondly, most climate phenomena are non-coocurring; with a majority exhibiting a bistable behavior (or positive/negatives phases). These allow us to tailor a subspace rotation that provides a good estimate of the underlying climate-associated pattern. Once the climate-associated pattern is isolated we can use it as a basis for building local climate indeces as well as for the validation of climate models.
