
====
While some complex land-air interactions are occuring,
an observer does not need to understand them to visually identify the climates in question.
The patterns are evident without any understanding of the physical mechanisms behind them.
This suggests that we should be able to estimate climate-associated patterns without understanding them.
The motivation for this is severalfold.
For one,
such a method would present an objective,
climate-agnostic,
first step in observing climate systems.
We would entirely avoid needing to characterize the climate system in question;
obviating the need for heuristics or thresholding systems based on past statistics
**(Rainy Season of the Asian Pacific Summer Monsoon - Bin Wang)**.
Furthermore,
we should be able to leverage more data and get higher fidelity than typical conservative methods,
such as JJA or DJF means.
Aspirationally,
we may in theory be able to explore new climate processes that have not yet been identified/characterized.
====





== SUPP: Error Analysis

For the purpose of this analysis we will not be considering instrument error as this goes in to the specifics of the IMERG system and is outside the scope of the method

The error propagation will be explained in several steps:

1. We first will characterize the noise
2. Then we will explain how it affects the projections in the SV1 SV2 subspace of FIG????
3. This then will establish an error of the climate patterns themselves (FIG?? FIG??)
4. After which we can estimate the error of the climate index - ie. the projections of the time points on to the climate patterns themselves.

=== 1: The Noise

The simplifying characteristic A1 tells us that if we remove the first two singular vectors we are left with an estimate of the noise component of the system.

.De-noised data (ie. data with SV1 and SV2 removed)
image::imrg/krabi/monthly/noise-all.svg[]

The de-signaled data,
as expected,
looks like noise with no discernible climate patterns.
This remaining noise should have an expected value of zero.
Any non-zero value would in-effect indicate some additional climate signal,
which would run counter to *A1*.

The noise's variance generally increases with an increase in monsoon signal.
Visually we saw in FIG??? that the monsoon pattern manifests unevenly.
Intuitively,
we expect that when there is little signal/monsoon thing are dryer and the noise level is reduced.
When the climate signal is strong the noise level is higher.
At such times some patches may remain entirely dry,
while others may have large amounts of precipitation.

To observe this,
we can re-plot the months by their power in SV1+SV2 compared to the power of the remaining SVs (SV3,SV4,SV5,..etc).

.Signal to Noise plot
image::imrg/krabi/monthly/power-sv12-vs-other.svg[]

Unfortunately,
while there is a general linear relationship,
it isn't very robust.
There are many outliers and a lot of variability.

=== 2. Error in the 2D SV1 SV2 subspace

The noise level is important because it affects our estimates of projections.
While the expected value of the noise is zero,
the actual mean will never be exactly zero.
The variance of the measured mean is akin to the classic standard deviation of the mean (SDOM).
When you project your data on to a pattern (ex: SV1 or SV2),
the mean of the noise in areas of the pattern will be folded in to the projection.
So when calculating the inner product of the pattern and measurement,
the noise will cause you to either overestimate or underestimate the strength of your signal.

So when we took our data points and placed them on the SV1 SV2 plot (FIG????),
we had implicitly done this projection.
The noise's mean at every point in time was folded into the projections and had skewed our results.
While the size of the skew can't be know directly,
the magnitude can be estimated by knowing the variance of the noise.

For the purpose of this analysis we treat the SV1 and SV2 patterns/vectors as both having negligible errors relative to the data.

.TODO:
IS THIS A SAFE ASSUMPTION? DO I NEED TO ESTIMATE THE ERROR OF THE SV? CAN BE DONE BY DIVIDING DATASET AND CALCULATING.. OR SOME BOOTSTRAP?

We had originally gotten the projections by looking at the left singular vectors of the SVD.
However,
if done explicitly,
the projecting is done by taking the inner product of the data and the pattern.
Note that the left singular vectors are unit length,
While the projections are not.
So the final errors need to be divided by the corresponding singular value to be at the same scale
In other words we go pixel by pixel multiplying the pattern *P* with the data *D* and summing them all up:

stem:[sum_(pxl=1)^n P_{pxl}*D_{pxl}]

The pattern pixels *P* have negligible errors so we treat them as constant.
The data pixels for each time point *D* are some signal *S* with some noise *N*

stem:[sum_(pxl=1)^n P_{pxl}*(S_{pxl} +- N_{pxl)}]

We can separate this into the original inner product and the sum of zero mean errors:

stem:[sum_(pxl=1)^n P_{pxl}*S_{pxl} +  sum_(pxl=1)^n 0 +- P_{pxl}*N_{pxl}]

The best estimate of *S* is *D* so the left hand side is just our original inner product.
The error of the sum of errors is their quadrature sum.
So the final inner product will be:

stem:[sum_(pxl=1)^n P_{pxl}*S_{pxl} +- sqrt(sum_(pxl=1)^n (P_{pxl}*N_{pxl})^2)]

The last step is deciding on a value for *N*.
One option is to use the linear relation from FIG????.
However this presupposes a constant noise power across the whole field and that the noise level is purely a function of the signal strength.
Fortunately since the patterns fields are large and since we have many pixels and can directly estimate the noise level at every point in time.
If we treat each pixel as a separate random process with mean zero and unknown standard deviation then the designaled data gives us one trial.
The absolute value of the designaled pixel is our best estimate of of the standard deviation *N*.
So the error estimate is quadrature sum of the product of the designalled data and the pattern.

At this step the pattern *P* is either *SV1* or *SV2*.
The quadrature sum, after dividing by the corresponding singular value, provides the X and Y error in FIG????.
Note also that a larger pattern will make the relative noise smaller.

image::imrg/krabi/monthly/sv-projs-with-errors.svg[]

=== 3. Error in climate pattern

Now each data point in the SV1 SV2 plane has X and Y errors which we will call dX and dY.
To find the ratio of SV1 and SV2 associate with each climate pattern,
we first need to calculate the associated ratio for each data point.
If we calculate X/Y for each point then the associate error is the sum in quadrature of the fractional uncertainties:

stem:[X/Y +- sqrt(((dX)/X)^{2} + ((dY)/Y)^{2}]

.TODO:
- RATIO SEEM PROBLEMATIC AS IT EXPLODES TO HUGE VALUES AS Y GOES TO ZERO.
- MAYBE RADIANS?
- MAYBE PERCENTAGE OF SV1? (X/(X+Y))

When calculating the averages and variances of each half we now use these ratios with their associated errors.
Assume the errors are independent and normally distributed,
we can use the variances to make a weighted average and calculate a weighted variance

https://en.wikipedia.org/wiki/Inverse-variance_weighting

.TODO:
- SHOULD I ADDRESS THE INDEPENDENT/NORMAL CRITERIA..?
- OR FIND AN ELEGANT WAY TO ACKNOWLEDGE AND SKIP IT..?

When the variance minimizing divider is found,
the average will yield a ratio that corresponds to each the climate pattern.
The associated variance will specify the error in that ratio.
We can then use the error in the SV1 SV2 ratio to calculate average + error and average - error patterns and thereby calculate a pixel level standard deviation.
Naturally areas with high values in SV1 and SV2 will result in higher errors.

THE ERRORS "BARS" ARE LIKELY NOT SYMMETRIC.. NOT SURE HOW TO HANDLE/DISPLAY

.TODO:
- A MAP OR THE ERRORS FOR SUMMER AND WINTER MONSOONS??

=== 4. Error in Climate Index

The final error to be determined is the error in the final calculated climate index.
This is the projection of each time/data point on to each climate pattern.
Here the procedure is the same as when we projected on to SV1 and SV2.
However, while we treated SV1 and SV2 as having no effective error,
here we treat the climate patterns as having an error.

stem:[sum_(pxl=1)^n P_{pxl}*D_{pxl}]

So in the previous equation both P and D now have an error associated with them.

stem:[sum_(pxl=1)^n P_{pxl}*S_{pxl} +- N_{pxl}]

Here N is the quadrature sum of the fractional uncertainties.
We then proceed as before doing a quadrature sum of these combined probabilities.
This gives us the error bars on the final climate index projections.



== SUPP Pattern separation at different time scales

In our primary case study we look at precipitation totals at the pentad scale.
This integration time, or time box size, was chosen to help illustrate the method.
It gives nice separation in the SV12 subspace while avoiding the issue of longer time-boxes.

In this section we will do a quick overview of the behavior seen with larger and smaller integration times


=== Large time boxes

We first look at the issues that arise with larger time windows by looking at the same region using monthly precpitation values.
Monthly maps are provided directly by the IMERG

TODO: IMAGE OF MONTHLY SV12

What we start to see is a proportion of the higher energy (ie. further from the origin) data points lie between the two climate clusters. A large fraction of these occur during the late Fall (purple/violet) and correspond to transition points. The change from Summer Monsoon to Winter monsoon occurs rapidly in the region. The month-long time box in effect captures a certain amount of summer monsoon, indeterminate transition state, and winter monsoon. The final monthly map looks like a mixture of the two monsoon signals! This is an aliasing-type problem that runs counter to the method's built-in assumption that the climate will never coocurring.

== Small time boxes

We can also decrease the time box size. Decreasing the time step effectively provides us with more data points for a give period of time. The practical limit is a daily average - as any smaller time increment would need to contend with diurnal variability. Diurnal climate patterns are definitely present, but the separation of diurnal climate systems from seasonal (and potentially interannual) patterns is an area for future work and outside the scope of the current method. At the daily time-scale we may still observe transitional states, where neither climate system is established and hence neither pattern is present. However, we become less likely to capture actual mixing of mutliple climate systems in one integration time-step

When we observe the SV1 SV2 subspace again, we no longer see a distinct two-cluster system. At first glance it looks like all points are a mixture of the end members.

TODO: Image of daily SV12 subspace

However when we do our variance minimization method and look at the two centroids we find that the resulting patterns are identical

TODO: Daily patterns


Replotting all the data's angular component - a histogram shows that in the cloud of points you are getting two peaks. Each point is just perturbed by such a large amount of noise that the previously distinct clusters are lost. Unfortunately the variability in this subspace greatly exceeds the variability estimates in our Error Analysis, which suggests there is some room for improvement.

Looking at this spread one can't help but notice the wedge-like shape. These top and bottom edges of the wedge are not mixing end-member but in effect delimit an "allowed" zone of SV1 SV2 mixtures. Note how SV2 has large positive and negative values. Projections outside these zones would represent in mixtures that result in large negative zones in these SV1, SV2 component sums. Since precipitation must always be positive, the remaining noise would need to "fill in" these negative zones - which becomes increasingly unlikely as the zone becomes larger.

Looking at the resulting climate index we can oberserve the monsoons at the daily scale with with effectively a lot of noise. Some days in the middle of the summer are classified as winter monsoon days and vice versa. Since we don't have a good characterization of the variability we leave providing a comprehensive methodology for interpreting misclassified days as an area for future work. Re-interpreting the data in pentads or other time slices at the climate index level could potentially provide resolve this issue, but would require some criteria of a new integration window. If you know the there is one climate transition per year (ex: summer to winter monsoon) one could potentially tailor a statistical method to detect this transition point

In short, smaller time steps do not hurt the climate pattern extraction process, but may create an extremely high resolution noisy climate index that is challenging to interpret.

== SUPP Rift Valley: Non cyclical signals

Unlike many EOF enhancements, the methodology as currently illustrated does not make any assumptions about climate variability over time. There are no assumptions that one climate follows another or that they occur at similar times of the year/day. This allows us to look at some more unusual climate phenomena such as the rain patters of the Rift Valley in Eastern Africa

TODO: All (monthly?) data

Here there are two rain-associated climate systems which in Ethiopia as called the Belg and the Kiremt

https://agupubs.onlinelibrary.wiley.com/doi/full/10.1002/2016RG000544

TODO: Read this thing..

While boreal summer Kiremt rains come at a consistent time every year, Belg "short" rains as a lot less consistent and associated . However the illutrated method has no issue extracting these patterns.

TODO: SV12 projs

TODO: Patterns

TOOO: Climate index


== SUPP: Sahel Mountain (Marrah): Method used in a one signal region
Maybe the most common instance would be the one monsoon-related rainy season.
At the seasonal scale,
these climate systems are may be more the norm than the exception.
In these degenerate cases SV1 will be giving you a good approximation of the climate related pattern.
No extra steps are needed.
Unfortunately,
at the moment there is no clear statistical method identifying which regions have climate dipoles.
An ad hoc method is looking at the singular values in a scree plot.
However,
there is no clear line between a two climate system and one where characteristic *A3* have broken down.
Non linearities in climate associated patterns may cause Onset/withdrawal periods to present patterns distinct from the main climate associated period.
For an example of this phenomena see the Marrah Plateau in **SUPP**
Such situations need to be identified by the researcher on a case-by-case basis.


It must be noted that globally, most locations do not feature a bistable climate. The most common scenario is a simple one-system precipitation climate (at the seasonal scale). In these locations no tricks are necessary. The first singular vector (or first EOF) will extract the single pattern.

So it is interesting to try to observe what occurs if we apply your method in these situations. As a case study we look at the Marrah mountains in southern Sudan. This massif lies at the edge of the Sahel and is subject to a single monsoon-driven rainy season. The massif's topography has some interplay with the monsoon related atmospheric configuration which drives the dominant precipitation pattern.

TODO: SV12 plot

First note that we no longer see a clear separation in the SV12 subspace. The data presents an even spread across the allowable wedge. The two extracted patterns no longer have a clear physical interpretations

TODO: Pattern 1 &2

But when we look at the resulting climate pattern we do see a consistent pattern

TODO: Climate index

The single pattern is being torn apart in to a monsoon signal and an onset/withdrawl pattern. Remember that one of the assumptions of the EOF  (A3) was that:
" The climate patterns in question scale in a near-linear fashion.
If it rains twice as much,
then it rains twice as much across the whole climate associated precipitation region"

Here we see this assumption fall apart as the weaker onset/withdrawl monsoon takes on a warped shaped as compared to the middle of the rainy season.
This onset/withdrawl false pattern occurs regularly when the method is applied in single-system regions and is a good indicator that the method should skipped in favor of simply using the first singular vector (or first EOF1).

A look at the singular values confirms also gives us a strong indication there is effectively no second climate system at the seasonal scale

== SUPP Diurnal cycles: Maritime continent
So far we have limited ourselves to seasonal climate systems. However the method may work at other time scales. Here we present a quick examination of the diurnal cycle off the coast of Java for the period (TODO Specify period):

TODO: Data image

Again IMERG can be used as it provides extremely high resolution data at the half hour interval

TODO: SV12 plot

We again get some separation ..

A lot of intermediary state

Very noisy input

But it kinda works..
And you can have a lot more input data

Watch out for seasonal signals.
Separation of signals at different time scales is outside the scope of the paper



== SUPP Korean Peninsula: Large Region vs Small Region

We noted in passing that working at the mesoscale allows us to get clear climate onset/withdrawl.
Here we present results when a region that is too large is used.
We look at the Korean Peninsular at two different scales

Things go bad


== SUPP: Notes on IMERG

For the Southern Thailand case study we selected to use the V06B Late data provided by IMERG (in GeoTIFF format). We find that other versions produce notable issues related to a "climatological adjustment" made using GPCC gauge data. This rain gauge correction was added to the "Final" version of version V06B. In version V07B the correction is incorporated in both Late and Final version. The Early version is still unaffected, however it "only has forward propagation (which basically amounts to extrapolation forward in time), while the Late has both forward and backward propagation (allowing interpolation)". See: https://gpm.nasa.gov/data/imerg FAQ Section.

The adjustment creates a notable stenciling effect. The stencil seems to reflect the GPCC stencil seen in GPCC precipitation maps:
https://climatedataguide.ucar.edu/climate-data/gpcc-global-precipitation-climatology-centre

Here is an example using v7 monthly data:

TODO add images

V06 is provided in several different subversion. One is labeled V06B and GeoTIFF files are provided through 2022-05-07. The next next period goes through multiple version through 2024-06-02. To avoid any discontinuities in the analysis. We look at v06B data exclusively on the 2011-01-01 to 2020-12-31 (inclusive) period.

To simplify the analysis and create even annual cycles we subdivide the 365 day calandar year into pentads by removing all occurances of the leap day - February 29th.



== Long Abstract

=== V1

The interplay between recurring atmospheric processes and local topography creates regular observable climatic phenomena.
We present a novel method for analyzing the spatial distribution of atmospheric parameters at the mesoscale,
which will allows for the extraction of a pair of underlying climate-associated shapes.
The method builds on the singular value decomposition (SVD) and corrects for several deficiencies of a typical empirical orthogonal function (EOF) analysis.
The extracted shapes act as unique fingerprints that allow one to observe climate without having to characterize it,
without needing to understand any of its dynamics,
and without building any heuristics or adjusting tuning parameters.
Key to making the EOF correction is recognizing that a large fraction of climate phenomena come in non-coocurring pairs.
Systems such as the Summer/Winter Monsoons,
El Nino / La Nina and the positive and negative phases of many climate systems are all typically in one of two modes.
In effect the presence of one climate state precludes the occurrence of the other.
As a result of this bistability,
when using the SVD to reduce the measured climate parameters to two dimensions we observe clustering around two linear combinations of the basis vectors.
These two combinations can be found using a variance minimizing search (Otsu's method) that terminates at an optimal solution and represent a simple mixture of the first two singular vectors.
The mixtures' associated shapes can then be used to measure the presence of the climate phenomena in the original data to build a rolling two state climate index.
We present several examples using the IMERG precipitation dataset,
the ERA5 precipitations model estimates and a small synthetic data example.
An accompanying program for reproducing the analysis is provided.


=== V2

Many climate phenomena historically aquire names by a process of pattern-matching by local observers.
In simple terms,
large scale climate conditions are observed to cause a higher likelyhood of some corresponding weather.
While the naming of phenomena is useful,
due to the inherant variability,
local weather observation are never sufficient for inferring the current climate state.
However,
by observing weather across a region,
(ie. many locales simultaneously)
we can start to make stronger inferrence about the prevailing large scale climate conditions.
The climate's statistically significant effect on the weather is complex and region specific.
Without characterizing any of the dynamics,
we can safely assume it will almost certainly be spatially irregular.
This will be due to some complex interplay between atmospheric parameters and the local topography.
Here we present a novel method for analyzing the spatial distribution of weather at the mesoscale.
By looking at weather over a given region we can extract each climate's associate associate patterns.
Then using the extracted spatial patterns we can reanalyze our weather's conformance to the pattern.
Thus allowing us to infer the prevailing climate conditions for a given point in time.
The method builds on the singular value decomposition (SVD).
We remove the need for working off of an anomaly -
as is seen in a typical empirical orthogonal function (EOF) analysis.
More importantly,
we find a way to resolve the EOFs orthogonality constraint.
Key to the new approach is recognizing that many climate phenomena come in non-coocurring pairs.
Systems such as the Summer/Winter Monsoons,
El Nino / La Nina as well as the positive and negative phases of many other climate dipoles.
The critical characteristic of a climate dipole is that the presence of one climate state precludes the occurrence of the other.
As a result of this bistability,
when the the measured climate parameters are reduced to two dimensions by SVD,
we observe clustering around two linear combinations of the basis vectors.
These two combinations can be isolated using a variance minimizing search (Otsu's method) that terminates at an optimal solution and represent a simple mixture of the first two singular vectors.
The mixtures can then be used to form the basis of a two state climate index.
We present several examples using the IMERG precipitation dataset,
the ERA5 precipitations model estimates and a small synthetic data example.
An accompanying program for reproducing the analysis is provided.


